// ==UserScript==
// @name UWA Auto EzProxy Redirector
// @namespace jtanx.plugins
// @description Automatically redirect to the proxified equivalent as provided by the University of Western Australia.
// @run-at document-start
// @grant none
// 
// @match http://*.repository.uwa.edu.au/*
// @match https://*.repository.uwa.edu.au/*
// @match http://*.cmo.library.uwa.edu.au/*
// @match https://*.cmo.library.uwa.edu.au/*
// @match http://*.cmo-devel.library.uwa.edu.au/*
// @match https://*.cmo-devel.library.uwa.edu.au/*
// @match http://*.my.uwa.edu.au/*
// @match https://*.my.uwa.edu.au/*
// @match http://*.uwa.eblib.com.au/*
// @match https://*.uwa.eblib.com.au/*
// @match http://*.australianmusiccentre.com.au/*
// @match https://*.australianmusiccentre.com.au/*
// @match http://*.vlearn.vea.com.au/*
// @match https://*.vlearn.vea.com.au/*
// @match http://*.forms.library.uwa.edu.au/*
// @match https://*.forms.library.uwa.edu.au/*
// @match http://*.theses.library.uwa.edu.au/*
// @match https://*.theses.library.uwa.edu.au/*
// @match http://*.static.library.uwa.edu.au/*
// @match https://*.static.library.uwa.edu.au/*
// @match http://*.aacrjournals.org/*
// @match https://*.aacrjournals.org/*
// @match http://*.aacr.org/*
// @match https://*.aacr.org/*
// @match http://*.aacrmeetingabstracts.org/*
// @match https://*.aacrmeetingabstracts.org/*
// @match http://*.aapgbulletin.datapages.com/*
// @match https://*.aapgbulletin.datapages.com/*
// @match http://*.search.ebscohost.com/*
// @match https://*.search.ebscohost.com/*
// @match http://*.ebooks.abc-clio.com/*
// @match https://*.ebooks.abc-clio.com/*
// @match http://*.accessengineeringlibrary.com/*
// @match https://*.accessengineeringlibrary.com/*
// @match http://*.accesspharmacy.mhmedical.com/*
// @match https://*.accesspharmacy.mhmedical.com/*
// @match http://*.portal.acm.org/*
// @match https://*.portal.acm.org/*
// @match http://*.pubs.acs.org/*
// @match https://*.pubs.acs.org/*
// @match http://*.acta.astrouw.edu.pl/*
// @match https://*.acta.astrouw.edu.pl/*
// @match http://*.actahort.org/*
// @match https://*.actahort.org/*
// @match http://*.actamathematica.org/*
// @match https://*.actamathematica.org/*
// @match http://*.acta.hu/*
// @match https://*.acta.hu/*
// @match http://*.app.pan.pl/*
// @match https://*.app.pan.pl/*
// @match http://*.architecture.com.au/*
// @match https://*.architecture.com.au/*
// @match http://*.ahajournals.org/*
// @match https://*.ahajournals.org/*
// @match http://*.aiaa.org/*
// @match https://*.aiaa.org/*
// @match http://*.aids-clinical-care.jwatch.org/*
// @match https://*.aids-clinical-care.jwatch.org/*
// @match http://*.humanitiesebook.org/*
// @match https://*.humanitiesebook.org/*
// @match http://*.search.alexanderstreet.com/*
// @match https://*.search.alexanderstreet.com/*
// @match http://*.akademiai.com/*
// @match https://*.akademiai.com/*
// @match http://*.astreetpress.com/*
// @match https://*.astreetpress.com/*
// @match http://*.ejournals.wspc.com.sg/*
// @match https://*.ejournals.wspc.com.sg/*
// @match http://*.neur.allenpress.com/*
// @match https://*.neur.allenpress.com/*
// @match http://*.intl.alphamedpress.org/*
// @match https://*.intl.alphamedpress.org/*
// @match http://*.aacc.org/*
// @match https://*.aacc.org/*
// @match http://*.aapm.org/*
// @match https://*.aapm.org/*
// @match http://*.jada.ada.org/*
// @match https://*.jada.ada.org/*
// @match http://*.aeaweb.org/*
// @match https://*.aeaweb.org/*
// @match http://*.agu.org/*
// @match https://*.agu.org/*
// @match http://*.intl.amjbot.org/*
// @match https://*.intl.amjbot.org/*
// @match http://*.ajcn.org/*
// @match https://*.ajcn.org/*
// @match http://*.ajhg.org/*
// @match https://*.ajhg.org/*
// @match http://*.amjpathol.org/*
// @match https://*.amjpathol.org/*
// @match http://*.ajp.press.uiuc.edu/*
// @match https://*.ajp.press.uiuc.edu/*
// @match http://*.ajsonline.org/*
// @match https://*.ajsonline.org/*
// @match http://*.ajtmh.org/*
// @match https://*.ajtmh.org/*
// @match http://*.ams.org/*
// @match https://*.ams.org/*
// @match http://*.minsocam.org/*
// @match https://*.minsocam.org/*
// @match http://*.aps.org/*
// @match https://*.aps.org/*
// @match http://*.physiology.org/*
// @match https://*.physiology.org/*
// @match http://*.the-aps.org/*
// @match https://*.the-aps.org/*
// @match http://*.amamanualofstyle.com/*
// @match https://*.amamanualofstyle.com/*
// @match http://*.alatechsource.metapress.com/*
// @match https://*.alatechsource.metapress.com/*
// @match http://*.alcts.metapress.com/*
// @match https://*.alcts.metapress.com/*
// @match http://*.journals.ametsoc.org/*
// @match https://*.journals.ametsoc.org/*
// @match http://*.agronomy.org/*
// @match https://*.agronomy.org/*
// @match http://*.ascb.org/*
// @match https://*.ascb.org/*
// @match http://*.asbmb.org/*
// @match https://*.asbmb.org/*
// @match http://*.ajcp.ascpjournals.org/*
// @match https://*.ajcp.ascpjournals.org/*
// @match http://*.horttech.ashspublications.org/*
// @match https://*.horttech.ashspublications.org/*
// @match http://*.hematology.org/*
// @match https://*.hematology.org/*
// @match http://*.jasn.asnjournals.org/*
// @match https://*.jasn.asnjournals.org/*
// @match http://*.asn-online.org/*
// @match https://*.asn-online.org/*
// @match http://*.atsjournals.org/*
// @match https://*.atsjournals.org/*
// @match http://*.annee-philologique.com/*
// @match https://*.annee-philologique.com/*
// @match http://*.anesthesiaprogress.org/*
// @match https://*.anesthesiaprogress.org/*
// @match http://*.annallergy.org/*
// @match https://*.annallergy.org/*
// @match http://*.annals.org/*
// @match https://*.annals.org/*
// @match http://*.annals.princeton.edu/*
// @match https://*.annals.princeton.edu/*
// @match http://*.theannals.com/*
// @match https://*.theannals.com/*
// @match http://*.annualreviews.org/*
// @match https://*.annualreviews.org/*
// @match http://*.imfareaer.org/*
// @match https://*.imfareaer.org/*
// @match http://*.anthrosource.net/*
// @match https://*.anthrosource.net/*
// @match http://*.antiquity.ac.uk/*
// @match https://*.antiquity.ac.uk/*
// @match http://*.content.apa.org/*
// @match https://*.content.apa.org/*
// @match http://*.adtmag.com/*
// @match https://*.adtmag.com/*
// @match http://*.apsjournals.apsnet.org/*
// @match https://*.apsjournals.apsnet.org/*
// @match http://*.artstor.org/*
// @match https://*.artstor.org/*
// @match http://*.ascelibrary.org/*
// @match https://*.ascelibrary.org/*
// @match http://*.asip.org/*
// @match https://*.asip.org/*
// @match http://*.aslo.org/*
// @match https://*.aslo.org/*
// @match http://*.products.asminternational.org/*
// @match https://*.products.asminternational.org/*
// @match http://*.asm.org/*
// @match https://*.asm.org/*
// @match http://*.elibrary.asabe.org/*
// @match https://*.elibrary.asabe.org/*
// @match http://*.asmedigitalcollection.asme.org/*
// @match https://*.asmedigitalcollection.asme.org/*
// @match http://*.aspectfinancial.com.au/*
// @match https://*.aspectfinancial.com.au/*
// @match http://*.aspetjournals.org/*
// @match https://*.aspetjournals.org/*
// @match http://*.asia-studies.com/*
// @match https://*.asia-studies.com/*
// @match http://*.afpe.org.uk/*
// @match https://*.afpe.org.uk/*
// @match http://*.crl.acrl.org/*
// @match https://*.crl.acrl.org/*
// @match http://*.journalsip.astm.org/*
// @match https://*.journalsip.astm.org/*
// @match http://*.enterprise.astm.org/*
// @match https://*.enterprise.astm.org/*
// @match http://*.oxford-auslawdictionary.com/*
// @match https://*.oxford-auslawdictionary.com/*
// @match http://*.austms.org.au/*
// @match https://*.austms.org.au/*
// @match http://*.onlinepublications.austroads.com.au/*
// @match https://*.onlinepublications.austroads.com.au/*
// @match http://*.abs.gov.au/*
// @match https://*.abs.gov.au/*
// @match http://*.austlit.edu.au/*
// @match https://*.austlit.edu.au/*
// @match http://*.asmjournals.org/*
// @match https://*.asmjournals.org/*
// @match http://*.eureka.rlg.org/*
// @match https://*.eureka.rlg.org/*
// @match http://*.journals.bcdecker.com/*
// @match https://*.journals.bcdecker.com/*
// @match http://*.bepress.com/*
// @match https://*.bepress.com/*
// @match http://*.waspress.co.uk/*
// @match https://*.waspress.co.uk/*
// @match http://*.begellhouse.com/*
// @match https://*.begellhouse.com/*
// @match http://*.ebooks.benthamscience.com/*
// @match https://*.ebooks.benthamscience.com/*
// @match http://*.bmc.lib.umich.edu/*
// @match https://*.bmc.lib.umich.edu/*
// @match http://*.apps.brepolis.net/*
// @match https://*.apps.brepolis.net/*
// @match http://*.autoweb.rlg.org/*
// @match https://*.autoweb.rlg.org/*
// @match http://*.biochemj.org/*
// @match https://*.biochemj.org/*
// @match http://*.bst.portlandpress.com/*
// @match https://*.bst.portlandpress.com/*
// @match http://*.biochemsoctrans.org/*
// @match https://*.biochemsoctrans.org/*
// @match http://*.biolbull.org/*
// @match https://*.biolbull.org/*
// @match http://*.biolreprod.org/*
// @match https://*.biolreprod.org/*
// @match http://*.biomedcentral.com/*
// @match https://*.biomedcentral.com/*
// @match http://*.ccforum.com/*
// @match https://*.ccforum.com/*
// @match http://*.alzres.com/*
// @match https://*.alzres.com/*
// @match http://*.arthritis-research.com/*
// @match https://*.arthritis-research.com/*
// @match http://*.breast-cancer-research.com/*
// @match https://*.breast-cancer-research.com/*
// @match http://*.genomebiology.com/*
// @match https://*.genomebiology.com/*
// @match http://*.genomemedicine.com/*
// @match https://*.genomemedicine.com/*
// @match http://*.stemcellres.com/*
// @match https://*.stemcellres.com/*
// @match http://*.biophysj.org/*
// @match https://*.biophysj.org/*
// @match http://*.sociologyencyclopedia.com/*
// @match https://*.sociologyencyclopedia.com/*
// @match http://*.blackwellreference.com/*
// @match https://*.blackwellreference.com/*
// @match http://*.blackwell-synergy.com/*
// @match https://*.blackwell-synergy.com/*
// @match http://*.bloodjournal.org/*
// @match https://*.bloodjournal.org/*
// @match http://*.bioscientifica.com/*
// @match https://*.bioscientifica.com/*
// @match http://*.dmfr.birjournals.org/*
// @match https://*.dmfr.birjournals.org/*
// @match http://*.journals.bmj.com/*
// @match https://*.journals.bmj.com/*
// @match http://*.journals.brepols.net/*
// @match https://*.journals.brepols.net/*
// @match http://*.brepols.metapress.com/*
// @match https://*.brepols.metapress.com/*
// @match http://*.bridgemaneducation.com/*
// @match https://*.bridgemaneducation.com/*
// @match http://*.referenceworks.brillonline.com/*
// @match https://*.referenceworks.brillonline.com/*
// @match http://*.brillonline.nl/*
// @match https://*.brillonline.nl/*
// @match http://*.nijhoffonline.nl/*
// @match https://*.nijhoffonline.nl/*
// @match http://*.britishacademy.universitypressscholarship.com/*
// @match https://*.britishacademy.universitypressscholarship.com/*
// @match http://*.bjp.rcpsych.org/*
// @match https://*.bjp.rcpsych.org/*
// @match http://*.britishperiodicals.chadwyck.co.uk/*
// @match https://*.britishperiodicals.chadwyck.co.uk/*
// @match http://*.pharmacopoeia.co.uk/*
// @match https://*.pharmacopoeia.co.uk/*
// @match http://*.abcb.gov.au/*
// @match https://*.abcb.gov.au/*
// @match http://*.bcaillustrated.com.au/*
// @match https://*.bcaillustrated.com.au/*
// @match http://*.businessnews.com.au/*
// @match https://*.businessnews.com.au/*
// @match http://*.bww.dnb.com.au/*
// @match https://*.bww.dnb.com.au/*
// @match http://*.butterworthsonline.com/*
// @match https://*.butterworthsonline.com/*
// @match http://*.cabdirect.org/*
// @match https://*.cabdirect.org/*
// @match http://*.cabi.org/*
// @match https://*.cabi.org/*
// @match http://*.caliber.ucpress.net/*
// @match https://*.caliber.ucpress.net/*
// @match http://*.histories.cambridge.org/*
// @match https://*.histories.cambridge.org/*
// @match http://*.universitypublishingonline.org/*
// @match https://*.universitypublishingonline.org/*
// @match http://*.journals.cambridge.org/*
// @match https://*.journals.cambridge.org/*
// @match http://*.uwa.cambridge.patron.eb20.com/*
// @match https://*.uwa.cambridge.patron.eb20.com/*
// @match http://*.csa3.com/*
// @match https://*.csa3.com/*
// @match http://*.caaa.ca/*
// @match https://*.caaa.ca/*
// @match http://*.journals.cms.math.ca/*
// @match https://*.journals.cms.math.ca/*
// @match http://*.cmaj.ca/*
// @match https://*.cmaj.ca/*
// @match http://*.canmin.org/*
// @match https://*.canmin.org/*
// @match http://*.pubservices.nrc-cnrc.ca/*
// @match https://*.pubservices.nrc-cnrc.ca/*
// @match http://*.lexxion.eu/*
// @match https://*.lexxion.eu/*
// @match http://*.ww3.cch.com.au:8080/*
// @match https://*.ww3.cch.com.au:8080/*
// @match http://*.ceda.com.au/*
// @match https://*.ceda.com.au/*
// @match http://*.cellbiolint.org/*
// @match https://*.cellbiolint.org/*
// @match http://*.cellpress.com/*
// @match https://*.cellpress.com/*
// @match http://*.eebo.chadwyck.com/*
// @match https://*.eebo.chadwyck.com/*
// @match http://*.iimp.chadwyck.com/*
// @match https://*.iimp.chadwyck.com/*
// @match http://*.iimpft.chadwyck.com/*
// @match https://*.iimpft.chadwyck.com/*
// @match http://*.charlestonco.com/*
// @match https://*.charlestonco.com/*
// @match http://*.chelonianjournals.org/*
// @match https://*.chelonianjournals.org/*
// @match http://*.csj.jp/*
// @match https://*.csj.jp/*
// @match http://*.chemnetbase.com/*
// @match https://*.chemnetbase.com/*
// @match http://*.chicagomanualofstyle.org/*
// @match https://*.chicagomanualofstyle.org/*
// @match http://*.oversea.cnki.net/*
// @match https://*.oversea.cnki.net/*
// @match http://*.pkulaw.cn/*
// @match https://*.pkulaw.cn/*
// @match http://*.cefc.com.hk/*
// @match https://*.cefc.com.hk/*
// @match http://*.cro3.org/*
// @match https://*.cro3.org/*
// @match http://*.citiprogram.org/*
// @match https://*.citiprogram.org/*
// @match http://*.shmu.alexanderstreet.com/*
// @match https://*.shmu.alexanderstreet.com/*
// @match http://*.classiques-garnier.com/*
// @match https://*.classiques-garnier.com/*
// @match http://*.uwau.classical.com/*
// @match https://*.uwau.classical.com/*
// @match http://*.aspresolver.com/*
// @match https://*.aspresolver.com/*
// @match http://*.clinchem.org/*
// @match https://*.clinchem.org/*
// @match http://*.clinicalevidence.bmj.com/*
// @match https://*.clinicalevidence.bmj.com/*
// @match http://*.clinicalkey.com/*
// @match https://*.clinicalkey.com/*
// @match http://*.clinicalevidence.org/*
// @match https://*.clinicalevidence.org/*
// @match http://*.cs.portlandpress.com/*
// @match https://*.cs.portlandpress.com/*
// @match http://*.update-software.com/*
// @match https://*.update-software.com/*
// @match http://*.cognet.mit.edu/*
// @match https://*.cognet.mit.edu/*
// @match http://*.comlaw.gov.au/*
// @match https://*.comlaw.gov.au/*
// @match http://*.biologists.org/*
// @match https://*.biologists.org/*
// @match http://*.biologists.com/*
// @match https://*.biologists.com/*
// @match http://*.computerworld.com.au/*
// @match https://*.computerworld.com.au/*
// @match http://*.connect4.com.au/*
// @match https://*.connect4.com.au/*
// @match http://*.connectweb.com.au/*
// @match https://*.connectweb.com.au/*
// @match http://*.oceanalaw.com/*
// @match https://*.oceanalaw.com/*
// @match http://*.asihcopeiaonline.org/*
// @match https://*.asihcopeiaonline.org/*
// @match http://*.cortex-online.org/*
// @match https://*.cortex-online.org/*
// @match http://*.library.cqpress.com/*
// @match https://*.library.cqpress.com/*
// @match http://*.crcnetbase.com/*
// @match https://*.crcnetbase.com/*
// @match http://*.credoreference.com/*
// @match https://*.credoreference.com/*
// @match http://*.edata-center.com/*
// @match https://*.edata-center.com/*
// @match http://*.dx.doi.org/*
// @match https://*.dx.doi.org/*
// @match http://*.publish.csiro.au/*
// @match https://*.publish.csiro.au/*
// @match http://*.clp.oxfordjournals.org/*
// @match https://*.clp.oxfordjournals.org/*
// @match http://*.web.ovid.unilinc.edu.au/*
// @match https://*.web.ovid.unilinc.edu.au/*
// @match http://*.current-reports.com/*
// @match https://*.current-reports.com/*
// @match http://*.datatrace.com/*
// @match https://*.datatrace.com/*
// @match http://*.datamonitor.com/*
// @match https://*.datamonitor.com/*
// @match http://*.dbpia.co.kr/*
// @match https://*.dbpia.co.kr/*
// @match http://*.datagold.com/*
// @match https://*.datagold.com/*
// @match http://*.gender.amdigital.co.uk/*
// @match https://*.gender.amdigital.co.uk/*
// @match http://*.dental-update.co.uk/*
// @match https://*.dental-update.co.uk/*
// @match http://*.dialogatsite.com/*
// @match https://*.dialogatsite.com/*
// @match http://*.dib.cambridge.org/*
// @match https://*.dib.cambridge.org/*
// @match http://*.dukeupress.edu/*
// @match https://*.dukeupress.edu/*
// @match http://*.dukejournals.org/*
// @match https://*.dukejournals.org/*
// @match http://*.dukemathjournal.org/*
// @match https://*.dukemathjournal.org/*
// @match http://*.earthmagazine.org/*
// @match https://*.earthmagazine.org/*
// @match http://*.exacteditions.com/*
// @match https://*.exacteditions.com/*
// @match http://*.esajournals.org/*
// @match https://*.esajournals.org/*
// @match http://*.edpsciences.org/*
// @match https://*.edpsciences.org/*
// @match http://*.europhysicsnews.org/*
// @match https://*.europhysicsnews.org/*
// @match http://*.aanda.org/*
// @match https://*.aanda.org/*
// @match http://*.euppublishing.com/*
// @match https://*.euppublishing.com/*
// @match http://*.editlib.org/*
// @match https://*.editlib.org/*
// @match http://*.educause.edu/*
// @match https://*.educause.edu/*
// @match http://*.elgaronline.com/*
// @match https://*.elgaronline.com/*
// @match http://*.electrochem.org/*
// @match https://*.electrochem.org/*
// @match http://*.ecsdl.org/*
// @match https://*.ecsdl.org/*
// @match http://*.e-enlightenment.com/*
// @match https://*.e-enlightenment.com/*
// @match http://*.expertconsultbook.com/*
// @match https://*.expertconsultbook.com/*
// @match http://*.emeraldinsight.com/*
// @match https://*.emeraldinsight.com/*
// @match http://*.empire.amdigital.co.uk/*
// @match https://*.empire.amdigital.co.uk/*
// @match http://*.igi-online.com/*
// @match https://*.igi-online.com/*
// @match http://*.oxford-naswsocialwork.com/*
// @match https://*.oxford-naswsocialwork.com/*
// @match http://*.press.endocrine.org/*
// @match https://*.press.endocrine.org/*
// @match http://*.engineeringvillage.com/*
// @match https://*.engineeringvillage.com/*
// @match http://*.justis.com/*
// @match https://*.justis.com/*
// @match http://*.engnetbase.com/*
// @match https://*.engnetbase.com/*
// @match http://*.edition.pagesuite-professional.co.uk/*
// @match https://*.edition.pagesuite-professional.co.uk/*
// @match http://*.envplan.com/*
// @match https://*.envplan.com/*
// @match http://*.yale.edu/*
// @match https://*.yale.edu/*
// @match http://*.eolss.net/*
// @match https://*.eolss.net/*
// @match http://*.equinoxpub.com/*
// @match https://*.equinoxpub.com/*
// @match http://*.hwwilsonweb.com/*
// @match https://*.hwwilsonweb.com/*
// @match http://*.vnweb.hwwilsonweb.com/*
// @match https://*.vnweb.hwwilsonweb.com/*
// @match http://*.edrs.com/*
// @match https://*.edrs.com/*
// @match http://*.estuariesandcoasts.org/*
// @match https://*.estuariesandcoasts.org/*
// @match http://*.etg.tg.com.au/*
// @match https://*.etg.tg.com.au/*
// @match http://*.erudit.org/*
// @match https://*.erudit.org/*
// @match http://*.europaworld.com/*
// @match https://*.europaworld.com/*
// @match http://*.eje-online.org/*
// @match https://*.eje-online.org/*
// @match http://*.ems-ph.org/*
// @match https://*.ems-ph.org/*
// @match http://*.erj.ersjournals.com/*
// @match https://*.erj.ersjournals.com/*
// @match http://*.evolutionary-ecology.com/*
// @match https://*.evolutionary-ecology.com/*
// @match http://*.ebmonline.org/*
// @match https://*.ebmonline.org/*
// @match http://*.digitaleditions.com.au/*
// @match https://*.digitaleditions.com.au/*
// @match http://*.libraryedition.com.au/*
// @match https://*.libraryedition.com.au/*
// @match http://*.f1000.com/*
// @match https://*.f1000.com/*
// @match http://*.fasebj.org/*
// @match https://*.fasebj.org/*
// @match http://*.fq.math.ca/*
// @match https://*.fq.math.ca/*
// @match http://*.infotrac.galegroup.com/*
// @match https://*.infotrac.galegroup.com/*
// @match http://*.finsia.com/*
// @match https://*.finsia.com/*
// @match http://*.fupress.net/*
// @match https://*.fupress.net/*
// @match http://*.flm-journal.org/*
// @match https://*.flm-journal.org/*
// @match http://*.fordham.universitypressscholarship.com/*
// @match https://*.fordham.universitypressscholarship.com/*
// @match http://*.atilf.fr/*
// @match https://*.atilf.fr/*
// @match http://*.futuremedicine.com/*
// @match https://*.futuremedicine.com/*
// @match http://*.find.galegroup.com/*
// @match https://*.find.galegroup.com/*
// @match http://*.gendatabaseonline.com/*
// @match https://*.gendatabaseonline.com/*
// @match http://*.genesdev.cshlp.org/*
// @match https://*.genesdev.cshlp.org/*
// @match http://*.genetics.org/*
// @match https://*.genetics.org/*
// @match http://*.geoscienceworld.org/*
// @match https://*.geoscienceworld.org/*
// @match http://*.csa.com/*
// @match https://*.csa.com/*
// @match http://*.icevirtuallibrary.com/*
// @match https://*.icevirtuallibrary.com/*
// @match http://*.GIDEONonline.net/*
// @match https://*.GIDEONonline.net/*
// @match http://*.portal.euromonitor.com/*
// @match https://*.portal.euromonitor.com/*
// @match http://*.www3.griffith.edu.au/*
// @match https://*.www3.griffith.edu.au/*
// @match http://*.ebooks.greenwood.com/*
// @match https://*.ebooks.greenwood.com/*
// @match http://*.groundimprovement.com/*
// @match https://*.groundimprovement.com/*
// @match http://*.guilfordjournals.com/*
// @match https://*.guilfordjournals.com/*
// @match http://*.hbcpnetbase.com/*
// @match https://*.hbcpnetbase.com/*
// @match http://*.accessmedicine.com/*
// @match https://*.accessmedicine.com/*
// @match http://*.hartjournals.co.uk/*
// @match https://*.hartjournals.co.uk/*
// @match http://*.hhpr.org/*
// @match https://*.hhpr.org/*
// @match http://*.ebooks.hcn.com.au/*
// @match https://*.ebooks.hcn.com.au/*
// @match http://*.heinonline.org/*
// @match https://*.heinonline.org/*
// @match http://*.henrystewart.metapress.com/*
// @match https://*.henrystewart.metapress.com/*
// @match http://*.hstalks.com/*
// @match https://*.hstalks.com/*
// @match http://*.hljournals.org/*
// @match https://*.hljournals.org/*
// @match http://*.heterocycles.jp/*
// @match https://*.heterocycles.jp/*
// @match http://*.highwire.stanford.edu/*
// @match https://*.highwire.stanford.edu/*
// @match http://*.hh.um.es/*
// @match https://*.hh.um.es/*
// @match http://*.historicbrass.org/*
// @match https://*.historicbrass.org/*
// @match http://*.serials.abc-clio.com/*
// @match https://*.serials.abc-clio.com/*
// @match http://*.math.uh.edu/*
// @match https://*.math.uh.edu/*
// @match http://*.parlipapers.chadwyck.co.uk/*
// @match https://*.parlipapers.chadwyck.co.uk/*
// @match http://*.clients.ibisworld.com.au/*
// @match https://*.clients.ibisworld.com.au/*
// @match http://*.ieeexplore.ieee.org/*
// @match https://*.ieeexplore.ieee.org/*
// @match http://*.books.igi-online.com/*
// @match https://*.books.igi-online.com/*
// @match http://*.services.igi-global.com/*
// @match https://*.services.igi-global.com/*
// @match http://*.portal.igpublish.com/*
// @match https://*.portal.igpublish.com/*
// @match http://*.iias.nl/*
// @match https://*.iias.nl/*
// @match http://*.old.iias.asia/*
// @match https://*.old.iias.asia/*
// @match http://*.cababstractsplus.org/*
// @match https://*.cababstractsplus.org/*
// @match http://*.incites.isiknowledge.com/*
// @match https://*.incites.isiknowledge.com/*
// @match http://*.inderscienceonline.com/*
// @match https://*.inderscienceonline.com/*
// @match http://*.indiaraj.amdigital.co.uk/*
// @match https://*.indiaraj.amdigital.co.uk/*
// @match http://*.iumj.indiana.edu/*
// @match https://*.iumj.indiana.edu/*
// @match http://*.cip.cornell.edu/*
// @match https://*.cip.cornell.edu/*
// @match http://*.iai.asm.org/*
// @match https://*.iai.asm.org/*
// @match http://*.infosci-books.com/*
// @match https://*.infosci-books.com/*
// @match http://*.journals.informs.org/*
// @match https://*.journals.informs.org/*
// @match http://*.informaworld.com/*
// @match https://*.informaworld.com/*
// @match http://*.informahealthcare.com/*
// @match https://*.informahealthcare.com/*
// @match http://*.i-law.com/*
// @match https://*.i-law.com/*
// @match http://*.search.informit.com.au/*
// @match https://*.search.informit.com.au/*
// @match http://*.ingentaconnect.com/*
// @match https://*.ingentaconnect.com/*
// @match http://*.ingentaselect.com/*
// @match https://*.ingentaselect.com/*
// @match http://*.icsd.fiz-karlsruhe.de/*
// @match https://*.icsd.fiz-karlsruhe.de/*
// @match http://*.iijournals.com/*
// @match https://*.iijournals.com/*
// @match http://*.intelliconnect.wkasiapacific.com/*
// @match https://*.intelliconnect.wkasiapacific.com/*
// @match http://*.aaiddjournals.org/*
// @match https://*.aaiddjournals.org/*
// @match http://*.ijdb.ehu.es/*
// @match https://*.ijdb.ehu.es/*
// @match http://*.communicationencyclopedia.com/*
// @match https://*.communicationencyclopedia.com/*
// @match http://*.ijocs.org/*
// @match https://*.ijocs.org/*
// @match http://*.ijee.dit.ie/*
// @match https://*.ijee.dit.ie/*
// @match http://*.intmedpress.com/*
// @match https://*.intmedpress.com/*
// @match http://*.brepolis.net/*
// @match https://*.brepolis.net/*
// @match http://*.imf.org/*
// @match https://*.imf.org/*
// @match http://*.imfstatistics.org/*
// @match https://*.imfstatistics.org/*
// @match http://*.intlpress.com/*
// @match https://*.intlpress.com/*
// @match http://*.journals.iucr.org/*
// @match https://*.journals.iucr.org/*
// @match http://*.intarch.ac.uk/*
// @match https://*.intarch.ac.uk/*
// @match http://*.onlinelibrary.wiley.com/*
// @match https://*.onlinelibrary.wiley.com/*
// @match http://*.intl.iovs.org/*
// @match https://*.intl.iovs.org/*
// @match http://*.oxia.ouplaw.com/*
// @match https://*.oxia.ouplaw.com/*
// @match http://*.iop.org/*
// @match https://*.iop.org/*
// @match http://*.content.iospress.com/*
// @match https://*.content.iospress.com/*
// @match http://*.webofknowledge.com/*
// @match https://*.webofknowledge.com/*
// @match http://*.apps.webofknowledge.com/*
// @match https://*.apps.webofknowledge.com/*
// @match http://*.researcherid.com/*
// @match https://*.researcherid.com/*
// @match http://*.ipasource.com/*
// @match https://*.ipasource.com/*
// @match http://*.ishib.org/*
// @match https://*.ishib.org/*
// @match http://*.sif.it/*
// @match https://*.sif.it/*
// @match http://*.itergateway.org/*
// @match https://*.itergateway.org/*
// @match http://*.iwaponline.com/*
// @match https://*.iwaponline.com/*
// @match http://*.jstage.jst.go.jp/*
// @match https://*.jstage.jst.go.jp/*
// @match http://*.joannabriggs.edu.au/*
// @match https://*.joannabriggs.edu.au/*
// @match http://*.connect.jbiconnectplus.org/*
// @match https://*.connect.jbiconnectplus.org/*
// @match http://*.jid.sagepub.com/*
// @match https://*.jid.sagepub.com/*
// @match http://*.lyellcollection.org/*
// @match https://*.lyellcollection.org/*
// @match http://*.asadl.org/*
// @match https://*.asadl.org/*
// @match http://*.african-archaeology.de/*
// @match https://*.african-archaeology.de/*
// @match http://*.agdevjournal.com/*
// @match https://*.agdevjournal.com/*
// @match http://*.jabfp.org/*
// @match https://*.jabfp.org/*
// @match http://*.japmaonline.org/*
// @match https://*.japmaonline.org/*
// @match http://*.journalofanimalscience.org/*
// @match https://*.journalofanimalscience.org/*
// @match http://*.quod.lib.umich.edu/*
// @match https://*.quod.lib.umich.edu/*
// @match http://*.sloan-c.org/*
// @match https://*.sloan-c.org/*
// @match http://*.intl.jbc.org/*
// @match https://*.intl.jbc.org/*
// @match http://*.ejbjs.org/*
// @match https://*.ejbjs.org/*
// @match http://*.jbmronline.com/*
// @match https://*.jbmronline.com/*
// @match http://*.jchemed.chem.wisc.edu/*
// @match https://*.jchemed.chem.wisc.edu/*
// @match http://*.jco.ascopubs.org/*
// @match https://*.jco.ascopubs.org/*
// @match http://*.psychiatrist.com/*
// @match https://*.psychiatrist.com/*
// @match http://*.jds.fass.org/*
// @match https://*.jds.fass.org/*
// @match http://*.jdentaled.org/*
// @match https://*.jdentaled.org/*
// @match http://*.gerontologist.gerontologyjournals.org/*
// @match https://*.gerontologist.gerontologyjournals.org/*
// @match http://*.iaglr.org/*
// @match https://*.iaglr.org/*
// @match http://*.journalofgreenbuilding.com/*
// @match https://*.journalofgreenbuilding.com/*
// @match http://*.jhortscib.org/*
// @match https://*.jhortscib.org/*
// @match http://*.jimmunol.org/*
// @match https://*.jimmunol.org/*
// @match http://*.jleukbio.org/*
// @match https://*.jleukbio.org/*
// @match http://*.jlr.org/*
// @match https://*.jlr.org/*
// @match http://*.jomms.org/*
// @match https://*.jomms.org/*
// @match http://*.jmecology.com/*
// @match https://*.jmecology.com/*
// @match http://*.jmd.amjpathol.org/*
// @match https://*.jmd.amjpathol.org/*
// @match http://*.jnrlse.org/*
// @match https://*.jnrlse.org/*
// @match http://*.jneurosci.org/*
// @match https://*.jneurosci.org/*
// @match http://*.www-thejns-net.org/*
// @match https://*.www-thejns-net.org/*
// @match http://*.jnabs.org/*
// @match https://*.jnabs.org/*
// @match http://*.jn.nutrition.org/*
// @match https://*.jn.nutrition.org/*
// @match http://*.jorthod.maneyjournals.org/*
// @match https://*.jorthod.maneyjournals.org/*
// @match http://*.jospt.org/*
// @match https://*.jospt.org/*
// @match http://*.journalofphilosophy.org/*
// @match https://*.journalofphilosophy.org/*
// @match http://*.joponline.org/*
// @match https://*.joponline.org/*
// @match http://*.jrm.medicaljournals.se/*
// @match https://*.jrm.medicaljournals.se/*
// @match http://*.jrheum.com/*
// @match https://*.jrheum.com/*
// @match http://*.jrheum.org/*
// @match https://*.jrheum.org/*
// @match http://*.journals.asha.org/*
// @match https://*.journals.asha.org/*
// @match http://*.jsad.com/*
// @match https://*.jsad.com/*
// @match http://*.jultrasoundmed.org/*
// @match https://*.jultrasoundmed.org/*
// @match http://*.jove.com/*
// @match https://*.jove.com/*
// @match http://*.opuluspress.se/*
// @match https://*.opuluspress.se/*
// @match http://*.jstor.org/*
// @match https://*.jstor.org/*
// @match http://*.plants.jstor.org/*
// @match https://*.plants.jstor.org/*
// @match http://*.justcite.com/*
// @match https://*.justcite.com/*
// @match http://*.uwa.kanopystreaming.com/*
// @match https://*.uwa.kanopystreaming.com/*
// @match http://*.karger.com/*
// @match https://*.karger.com/*
// @match http://*.content.karger.com/*
// @match https://*.content.karger.com/*
// @match http://*.rbgkew.org.uk/*
// @match https://*.rbgkew.org.uk/*
// @match http://*.klapp-online.de/*
// @match https://*.klapp-online.de/*
// @match http://*.kluwerarbitration.com/*
// @match https://*.kluwerarbitration.com/*
// @match http://*.kluweronline.com/*
// @match https://*.kluweronline.com/*
// @match http://*.kluwerlawonline.com/*
// @match https://*.kluwerlawonline.com/*
// @match http://*.knovel.com/*
// @match https://*.knovel.com/*
// @match http://*.labanimal.com/*
// @match https://*.labanimal.com/*
// @match http://*.thelancet.com/*
// @match https://*.thelancet.com/*
// @match http://*.revues.armand-colin.com/*
// @match https://*.revues.armand-colin.com/*
// @match http://*.tla.thomson.com.au/*
// @match https://*.tla.thomson.com.au/*
// @match http://*.subscriber.lawbookco.com.au/*
// @match https://*.subscriber.lawbookco.com.au/*
// @match http://*.lcoastpress.com/*
// @match https://*.lcoastpress.com/*
// @match http://*.my.lawlex.com.au/*
// @match https://*.my.lawlex.com.au/*
// @match http://*.llama.metapress.com/*
// @match https://*.llama.metapress.com/*
// @match http://*.librarymusicsource.com/*
// @match https://*.librarymusicsource.com/*
// @match http://*.leme.library.utoronto.ca/*
// @match https://*.leme.library.utoronto.ca/*
// @match http://*.lexisnexis.com.au/*
// @match https://*.lexisnexis.com.au/*
// @match http://*.librariesaustralia.nla.gov.au/*
// @match https://*.librariesaustralia.nla.gov.au/*
// @match http://*.online.liebertpub.com/*
// @match https://*.online.liebertpub.com/*
// @match http://*.litencyc.com/*
// @match https://*.litencyc.com/*
// @match http://*.literatureencyclopedia.com/*
// @match https://*.literatureencyclopedia.com/*
// @match http://*.lion.chadwyck.co.uk/*
// @match https://*.lion.chadwyck.co.uk/*
// @match http://*.londonlowlife.amdigital.co.uk/*
// @match https://*.londonlowlife.amdigital.co.uk/*
// @match http://*.lrb.co.uk/*
// @match https://*.lrb.co.uk/*
// @match http://*.lupjournals.org/*
// @match https://*.lupjournals.org/*
// @match http://*.macquariedictionary.com.au/*
// @match https://*.macquariedictionary.com.au/*
// @match http://*.maneyonline.com/*
// @match https://*.maneyonline.com/*
// @match http://*.mrlonline.org/*
// @match https://*.mrlonline.org/*
// @match http://*.msp.org/*
// @match https://*.msp.org/*
// @match http://*.mathscipub.org/*
// @match https://*.mathscipub.org/*
// @match http://*.mathnetbase.com/*
// @match https://*.mathnetbase.com/*
// @match http://*.opil.ouplaw.com/*
// @match https://*.opil.ouplaw.com/*
// @match http://*.online.medphys.org/*
// @match https://*.online.medphys.org/*
// @match http://*.mja.com.au/*
// @match https://*.mja.com.au/*
// @match http://*.medicalevidencematters.com/*
// @match https://*.medicalevidencematters.com/*
// @match http://*.medici.tv/*
// @match https://*.medici.tv/*
// @match http://*.medicinescomplete.com/*
// @match https://*.medicinescomplete.com/*
// @match http://*.mergentonline.com/*
// @match https://*.mergentonline.com/*
// @match http://*.metapress.com/*
// @match https://*.metapress.com/*
// @match http://*.sanbi.co.jp/*
// @match https://*.sanbi.co.jp/*
// @match http://*.micromedexsolutions.com/*
// @match https://*.micromedexsolutions.com/*
// @match http://*.search.micronexx.com/*
// @match https://*.search.micronexx.com/*
// @match http://*.mimsonline.com.au/*
// @match https://*.mimsonline.com.au/*
// @match http://*.mitpressjournals.org/*
// @match https://*.mitpressjournals.org/*
// @match http://*.collections.chadwyck.co.uk/*
// @match https://*.collections.chadwyck.co.uk/*
// @match http://*.mlajournals.org/*
// @match https://*.mlajournals.org/*
// @match http://*.publications.epress.monash.edu/*
// @match https://*.publications.epress.monash.edu/*
// @match http://*.mcponline.org/*
// @match https://*.mcponline.org/*
// @match http://*.epress.monash.edu/*
// @match https://*.epress.monash.edu/*
// @match http://*.publishing.monash.edu/*
// @match https://*.publishing.monash.edu/*
// @match http://*.morganclaypool.com/*
// @match https://*.morganclaypool.com/*
// @match http://*.datanalysis.morningstar.com.au/*
// @match https://*.datanalysis.morningstar.com.au/*
// @match http://*.multi-science.metapress.com/*
// @match https://*.multi-science.metapress.com/*
// @match http://*.jmpt.hcn.com.au/*
// @match https://*.jmpt.hcn.com.au/*
// @match http://*.msa.org.au/*
// @match https://*.msa.org.au/*
// @match http://*.musicforum.org.au/*
// @match https://*.musicforum.org.au/*
// @match http://*.muco.alexanderstreet.com/*
// @match https://*.muco.alexanderstreet.com/*
// @match http://*.myilibrary.com/*
// @match https://*.myilibrary.com/*
// @match http://*.myrmecologicalnews.org/*
// @match https://*.myrmecologicalnews.org/*
// @match http://*.periodicals.narr.de/*
// @match https://*.periodicals.narr.de/*
// @match http://*.nature.com/*
// @match https://*.nature.com/*
// @match http://*.uwa.naxosvideolibrary.com/*
// @match https://*.uwa.naxosvideolibrary.com/*
// @match http://*.uwa.naxosmusiclibrary.com/*
// @match https://*.uwa.naxosmusiclibrary.com/*
// @match http://*.nber.org/*
// @match https://*.nber.org/*
// @match http://*.nearmap.com/*
// @match https://*.nearmap.com/*
// @match http://*.neilsonjournals.com/*
// @match https://*.neilsonjournals.com/*
// @match http://*.neoreviews.aappublications.org/*
// @match https://*.neoreviews.aappublications.org/*
// @match http://*.nejm.org/*
// @match https://*.nejm.org/*
// @match http://*.nejm.highwire.org/*
// @match https://*.nejm.highwire.org/*
// @match http://*.newleftreview.org/*
// @match https://*.newleftreview.org/*
// @match http://*.dictionaryofeconomics.com/*
// @match https://*.dictionaryofeconomics.com/*
// @match http://*.nybooks.com/*
// @match https://*.nybooks.com/*
// @match http://*.pacificarchaeology.org/*
// @match https://*.pacificarchaeology.org/*
// @match http://*.journal.nzma.org.nz/*
// @match https://*.journal.nzma.org.nz/*
// @match http://*.c19.chadwyck.co.uk/*
// @match https://*.c19.chadwyck.co.uk/*
// @match http://*.nowpublishers.com/*
// @match https://*.nowpublishers.com/*
// @match http://*.nrcresearchpress.com/*
// @match https://*.nrcresearchpress.com/*
// @match http://*.mcom.alexanderstreet.com/*
// @match https://*.mcom.alexanderstreet.com/*
// @match http://*.nursingreview.com.au/*
// @match https://*.nursingreview.com.au/*
// @match http://*.statistics.gov.uk/*
// @match https://*.statistics.gov.uk/*
// @match http://*.ojps.aip.org/*
// @match https://*.ojps.aip.org/*
// @match http://*.oldenbourg-link.com/*
// @match https://*.oldenbourg-link.com/*
// @match http://*.onarchitecture.com/*
// @match https://*.onarchitecture.com/*
// @match http://*.mathjournals.org/*
// @match https://*.mathjournals.org/*
// @match http://*.onemine.org/*
// @match https://*.onemine.org/*
// @match http://*.openbookpublishers.com/*
// @match https://*.openbookpublishers.com/*
// @match http://*.jopdentonline.org/*
// @match https://*.jopdentonline.org/*
// @match http://*.opticsinfobase.org/*
// @match https://*.opticsinfobase.org/*
// @match http://*.orchestralmusic.com/*
// @match https://*.orchestralmusic.com/*
// @match http://*.ovidsp.ovid.com/*
// @match https://*.ovidsp.ovid.com/*
// @match http://*.somme.library.uwa.edu.au/*
// @match https://*.somme.library.uwa.edu.au/*
// @match http://*.oldcitypublishing.com/*
// @match https://*.oldcitypublishing.com/*
// @match http://*.atypon-link.com/*
// @match https://*.atypon-link.com/*
// @match http://*.access.ovid.com/*
// @match https://*.access.ovid.com/*
// @match http://*.online.factsandcomparisons.com/*
// @match https://*.online.factsandcomparisons.com/*
// @match http://*.advisor.lww.com/*
// @match https://*.advisor.lww.com/*
// @match http://*.oxfordartonline.com/*
// @match https://*.oxfordartonline.com/*
// @match http://*.oxfordbibliographies.com/*
// @match https://*.oxfordbibliographies.com/*
// @match http://*.oxforddnb.com/*
// @match https://*.oxforddnb.com/*
// @match http://*.oxford-humanrights.com/*
// @match https://*.oxford-humanrights.com/*
// @match http://*.oxford-economichistory.com/*
// @match https://*.oxford-economichistory.com/*
// @match http://*.oxford-theatreandperformance.com/*
// @match https://*.oxford-theatreandperformance.com/*
// @match http://*.oxfordhandbooks.com/*
// @match https://*.oxfordhandbooks.com/*
// @match http://*.oxfordwesternmusic.com/*
// @match https://*.oxfordwesternmusic.com/*
// @match http://*.acn.oxfordjournals.org/*
// @match https://*.acn.oxfordjournals.org/*
// @match http://*.oed.com/*
// @match https://*.oed.com/*
// @match http://*.oxfordjournals.org/*
// @match https://*.oxfordjournals.org/*
// @match http://*.jwelb.oxfordjournals.org/*
// @match https://*.jwelb.oxfordjournals.org/*
// @match http://*.oxfordmusiconline.com/*
// @match https://*.oxfordmusiconline.com/*
// @match http://*.oxfordreference.com/*
// @match https://*.oxfordreference.com/*
// @match http://*.oxfordscholarship.com/*
// @match https://*.oxfordscholarship.com/*
// @match http://*.pjm.math.berkeley.edu/*
// @match https://*.pjm.math.berkeley.edu/*
// @match http://*.museumoftheearth.org/*
// @match https://*.museumoftheearth.org/*
// @match http://*.palgrave-journals.com/*
// @match https://*.palgrave-journals.com/*
// @match http://*.geo.arizona.edu/*
// @match https://*.geo.arizona.edu/*
// @match http://*.pediatrics.aappublications.org/*
// @match https://*.pediatrics.aappublications.org/*
// @match http://*.poj.peeters-leuven.be/*
// @match https://*.poj.peeters-leuven.be/*
// @match http://*.perceptionweb.com/*
// @match https://*.perceptionweb.com/*
// @match http://*.pci.chadwyck.com/*
// @match https://*.pci.chadwyck.com/*
// @match http://*.pio.chadwyck.co.uk/*
// @match https://*.pio.chadwyck.co.uk/*
// @match http://*.pao.chadwyck.co.uk/*
// @match https://*.pao.chadwyck.co.uk/*
// @match http://*.kappanmagazine.org/*
// @match https://*.kappanmagazine.org/*
// @match http://*.pdcnet.org/*
// @match https://*.pdcnet.org/*
// @match http://*.thephilosophersmagazine.com/*
// @match https://*.thephilosophersmagazine.com/*
// @match http://*.philpapers.org/*
// @match https://*.philpapers.org/*
// @match http://*.phycologia.org/*
// @match https://*.phycologia.org/*
// @match http://*.physicsworldarchive.iop.org/*
// @match https://*.physicsworldarchive.iop.org/*
// @match http://*.physsportsmed.com/*
// @match https://*.physsportsmed.com/*
// @match http://*.piprofiler.systematics.net.au/*
// @match https://*.piprofiler.systematics.net.au/*
// @match http://*.pidgeondigital.com/*
// @match https://*.pidgeondigital.com/*
// @match http://*.plantcell.org/*
// @match https://*.plantcell.org/*
// @match http://*.plantphysiol.org/*
// @match https://*.plantphysiol.org/*
// @match http://*.polymersdatabase.com/*
// @match https://*.polymersdatabase.com/*
// @match http://*.dlib.eastview.com/*
// @match https://*.dlib.eastview.com/*
// @match http://*.ps.fass.org/*
// @match https://*.ps.fass.org/*
// @match http://*.pnas.org/*
// @match https://*.pnas.org/*
// @match http://*.sciquest.org.nz/*
// @match https://*.sciquest.org.nz/*
// @match http://*.presidian.com.au/*
// @match https://*.presidian.com.au/*
// @match http://*.library.pressdisplay.com/*
// @match https://*.library.pressdisplay.com/*
// @match http://*.sleepmedtext.com/*
// @match https://*.sleepmedtext.com/*
// @match http://*.projecteuclid.org/*
// @match https://*.projecteuclid.org/*
// @match http://*.muse.jhu.edu.au/*
// @match https://*.muse.jhu.edu.au/*
// @match http://*.search.proquest.com/*
// @match https://*.search.proquest.com/*
// @match http://*.proteinscience.org/*
// @match https://*.proteinscience.org/*
// @match http://*.psychiatryonline.org/*
// @match https://*.psychiatryonline.org/*
// @match http://*.psychonomic-journals.org/*
// @match https://*.psychonomic-journals.org/*
// @match http://*.publichealthreports.org/*
// @match https://*.publichealthreports.org/*
// @match http://*.library.queensu.ca/*
// @match https://*.library.queensu.ca/*
// @match http://*.pubs.rsna.org/*
// @match https://*.pubs.rsna.org/*
// @match http://*.srmjournals.org/*
// @match https://*.srmjournals.org/*
// @match http://*.reproduction-online.org/*
// @match https://*.reproduction-online.org/*
// @match http://*.biblioline.nisc.com/*
// @match https://*.biblioline.nisc.com/*
// @match http://*.db.riskwaters.com/*
// @match https://*.db.riskwaters.com/*
// @match http://*.rockefeller.edu/*
// @match https://*.rockefeller.edu/*
// @match http://*.jem.org/*
// @match https://*.jem.org/*
// @match http://*.rupress.org/*
// @match https://*.rupress.org/*
// @match http://*.rmmc.eas.asu.edu/*
// @match https://*.rmmc.eas.asu.edu/*
// @match http://*.romanticism.amdigital.co.uk/*
// @match https://*.romanticism.amdigital.co.uk/*
// @match http://*.rep.routledge.com/*
// @match https://*.rep.routledge.com/*
// @match http://*.rsc.org/*
// @match https://*.rsc.org/*
// @match http://*.rsnz.org/*
// @match https://*.rsnz.org/*
// @match http://*.journals.royalsociety.org/*
// @match https://*.journals.royalsociety.org/*
// @match http://*.royalsocietypublishing.org/*
// @match https://*.royalsocietypublishing.org/*
// @match http://*.csu.edu.au/*
// @match https://*.csu.edu.au/*
// @match http://*.escarpmentpress.org/*
// @match https://*.escarpmentpress.org/*
// @match http://*.reference.sabinet.co.za/*
// @match https://*.reference.sabinet.co.za/*
// @match http://*.digitallibrary.sae.org/*
// @match https://*.digitallibrary.sae.org/*
// @match http://*.sage-ereference.com/*
// @match https://*.sage-ereference.com/*
// @match http://*.knowledge.sagepub.com/*
// @match https://*.knowledge.sagepub.com/*
// @match http://*.online.sagepub.com/*
// @match https://*.online.sagepub.com/*
// @match http://*.sauerlaender-verlag.com/*
// @match https://*.sauerlaender-verlag.com/*
// @match http://*.schattauer.de/*
// @match https://*.schattauer.de/*
// @match http://*.sciandmed.com/*
// @match https://*.sciandmed.com/*
// @match http://*.trrjournalonline.trb.org/*
// @match https://*.trrjournalonline.trb.org/*
// @match http://*.wssajournals.org/*
// @match https://*.wssajournals.org/*
// @match http://*.hub.sciverse.com/*
// @match https://*.hub.sciverse.com/*
// @match http://*.sciencedirect.com/*
// @match https://*.sciencedirect.com/*
// @match http://*.scopus.com/*
// @match https://*.scopus.com/*
// @match http://*.sciencemag.org/*
// @match https://*.sciencemag.org/*
// @match http://*.sos.thieme.com/*
// @match https://*.sos.thieme.com/*
// @match http://*.utpjournals.metapress.com/*
// @match https://*.utpjournals.metapress.com/*
// @match http://*.sex.sagepub.com/*
// @match https://*.sex.sagepub.com/*
// @match http://*.sjmjournals.org/*
// @match https://*.sjmjournals.org/*
// @match http://*.shancocksltd.co.uk/*
// @match https://*.shancocksltd.co.uk/*
// @match http://*.epubs.siam.org/*
// @match https://*.epubs.siam.org/*
// @match http://*.journalsleep.org/*
// @match https://*.journalsleep.org/*
// @match http://*.glmu.alexanderstreet.com/*
// @match https://*.glmu.alexanderstreet.com/*
// @match http://*.sfaa.metapress.com/*
// @match https://*.sfaa.metapress.com/*
// @match http://*.endocrinology-journals.org/*
// @match https://*.endocrinology-journals.org/*
// @match http://*.library.seg.org/*
// @match https://*.library.seg.org/*
// @match http://*.sgm.ac.uk/*
// @match https://*.sgm.ac.uk/*
// @match http://*.rangelands.org/*
// @match https://*.rangelands.org/*
// @match http://*.journalofrheology.org/*
// @match https://*.journalofrheology.org/*
// @match http://*.ssr.org/*
// @match https://*.ssr.org/*
// @match http://*.oecd-ilibrary.org/*
// @match https://*.oecd-ilibrary.org/*
// @match http://*.oecd-nea.org/*
// @match https://*.oecd-nea.org/*
// @match http://*.oecdobserver.org/*
// @match https://*.oecdobserver.org/*
// @match http://*.new.sourceoecd.org/*
// @match https://*.new.sourceoecd.org/*
// @match http://*.spe.org/*
// @match https://*.spe.org/*
// @match http://*.spiedigitallibrary.org/*
// @match https://*.spiedigitallibrary.org/*
// @match http://*.ebooks.spiedigitallibrary.org/*
// @match https://*.ebooks.spiedigitallibrary.org/*
// @match http://*.spiedigitallibrary.aip.org/*
// @match https://*.spiedigitallibrary.aip.org/*
// @match http://*.journals.spiedigitallibrary.org/*
// @match https://*.journals.spiedigitallibrary.org/*
// @match http://*.opticalengineering.spiedigitallibrary.org/*
// @match https://*.opticalengineering.spiedigitallibrary.org/*
// @match http://*.biomedicaloptics.spiedigitallibrary.org/*
// @match https://*.biomedicaloptics.spiedigitallibrary.org/*
// @match http://*.link.springer.de/*
// @match https://*.link.springer.de/*
// @match http://*.link.springer.com/*
// @match https://*.link.springer.com/*
// @match http://*.materials.springer.com/*
// @match https://*.materials.springer.com/*
// @match http://*.saiglobal.com/*
// @match https://*.saiglobal.com/*
// @match http://*.stata-journal.com/*
// @match https://*.stata-journal.com/*
// @match http://*.stat.sinica.edu.tw/*
// @match https://*.stat.sinica.edu.tw/*
// @match http://*.statindex.org/*
// @match https://*.statindex.org/*
// @match http://*.stahlonline.cambridge.org/*
// @match https://*.stahlonline.cambridge.org/*
// @match http://*.surgeryjournal.co.uk/*
// @match https://*.surgeryjournal.co.uk/*
// @match http://*.hcn.net.au/*
// @match https://*.hcn.net.au/*
// @match http://*.law.usyd.edu.au/*
// @match https://*.law.usyd.edu.au/*
// @match http://*.archives.smh.com.au/*
// @match https://*.archives.smh.com.au/*
// @match http://*.arabidopsis.org/*
// @match https://*.arabidopsis.org/*
// @match http://*.tax.thomsonreuters.com.au/*
// @match https://*.tax.thomsonreuters.com.au/*
// @match http://*.tl2.idcpublishers.info/*
// @match https://*.tl2.idcpublishers.info/*
// @match http://*.tandfonline.com/*
// @match https://*.tandfonline.com/*
// @match http://*.technopress.kaist.ac.kr/*
// @match https://*.technopress.kaist.ac.kr/*
// @match http://*.journal.telospress.com/*
// @match https://*.journal.telospress.com/*
// @match http://*.terrapub.co.jp/*
// @match https://*.terrapub.co.jp/*
// @match http://*.jep.textrum.com/*
// @match https://*.jep.textrum.com/*
// @match http://*.economist.com/*
// @match https://*.economist.com/*
// @match http://*.stephanus.tlg.uci.edu/*
// @match https://*.stephanus.tlg.uci.edu/*
// @match http://*.xroads.virginia.edu/*
// @match https://*.xroads.virginia.edu/*
// @match http://*.theshakespearerecords.com/*
// @match https://*.theshakespearerecords.com/*
// @match http://*.escj.org/*
// @match https://*.escj.org/*
// @match http://*.archive.thewest.com.au/*
// @match https://*.archive.thewest.com.au/*
// @match http://*.thomastelford.com/*
// @match https://*.thomastelford.com/*
// @match http://*.tlemea.com/*
// @match https://*.tlemea.com/*
// @match http://*.archive.scijournal.com/*
// @match https://*.archive.scijournal.com/*
// @match http://*.transactionpub.metapress.com/*
// @match https://*.transactionpub.metapress.com/*
// @match http://*.trb.metapress.com/*
// @match https://*.trb.metapress.com/*
// @match http://*.scientific.net/*
// @match https://*.scientific.net/*
// @match http://*.triangle.co.uk/*
// @match https://*.triangle.co.uk/*
// @match http://*.turf.lib.msu.edu/*
// @match https://*.turf.lib.msu.edu/*
// @match http://*.turpion.org/*
// @match https://*.turpion.org/*
// @match http://*.ulrichsweb.serialssolutions.com/*
// @match https://*.ulrichsweb.serialssolutions.com/*
// @match http://*.untreaty.un.org/*
// @match https://*.untreaty.un.org/*
// @match http://*.157.150.195.4/*
// @match https://*.157.150.195.4/*
// @match http://*.journals.uchicago.edu/*
// @match https://*.journals.uchicago.edu/*
// @match http://*.press.uillinois.edu/*
// @match https://*.press.uillinois.edu/*
// @match http://*.uwpress.org/*
// @match https://*.uwpress.org/*
// @match http://*.universitypressscholarship.com/*
// @match https://*.universitypressscholarship.com/*
// @match http://*.v-r.de/*
// @match https://*.v-r.de/*
// @match http://*.wileyonlinelibrary.com/*
// @match https://*.wileyonlinelibrary.com/*
// @match http://*.wlt.metapress.com/*
// @match https://*.wlt.metapress.com/*
// @match http://*.elib.library.uwa.edu.au/*
// @match https://*.elib.library.uwa.edu.au/*
// @match http://*.erl.library.uwa.edu.au:8050/*
// @match https://*.erl.library.uwa.edu.au:8050/*
// @match http://*.etext.library.uwa.edu.au/*
// @match https://*.etext.library.uwa.edu.au/*
// @match http://*.findit.library.uwa.edu.au/*
// @match https://*.findit.library.uwa.edu.au/*
// @match http://*.victoriandatabase.com/*
// @match https://*.victoriandatabase.com/*
// @match http://*.degruyter.com/*
// @match https://*.degruyter.com/*
// @match http://*.victorianperiodicals.com/*
// @match https://*.victorianperiodicals.com/*
// @match http://*.wellesley.chadwyck.co.uk/*
// @match https://*.wellesley.chadwyck.co.uk/*
// @match http://*.web5s.silverplatter.com/*
// @match https://*.web5s.silverplatter.com/*
// @match http://*.westlaw.com.au/*
// @match https://*.westlaw.com.au/*
// @match http://*.login.westlaw.co.uk/*
// @match https://*.login.westlaw.co.uk/*
// @match http://*.westlaw.com/*
// @match https://*.westlaw.com/*
// @match http://*.hw.oeaw.ac.at/*
// @match https://*.hw.oeaw.ac.at/*
// @match http://*.withoutsanctuary.org/*
// @match https://*.withoutsanctuary.org/*
// @match http://*.journals.witpress.com/*
// @match https://*.journals.witpress.com/*
// @match http://*.worldbank.org/*
// @match https://*.worldbank.org/*
// @match http://*.newfirstsearch.oclc.org/*
// @match https://*.newfirstsearch.oclc.org/*
// @match http://*.worldcatlibraries.org/*
// @match https://*.worldcatlibraries.org/*
// @match http://*.worldscinet.com/*
// @match https://*.worldscinet.com/*
// @match http://*.worldscientific.com/*
// @match https://*.worldscientific.com/*
// @match http://*.ebooks.worldscinet.com/*
// @match https://*.ebooks.worldscinet.com/*
// @match http://*.worldshakesbib.org/*
// @match https://*.worldshakesbib.org/*
// @match http://*.naa12.naa.gov.au/*
// @match https://*.naa12.naa.gov.au/*
// @match http://*.meddent.uwa.edu.au/*
// @match https://*.meddent.uwa.edu.au/*
// ==/UserScript==

window.location.replace(window.location.href.replace(/(https?:\/\/)([^\/]+)(.*)/i, "$1$2.ezproxy.library.uwa.edu.au$3"))
