// ==UserScript==
// @name UWA Auto EzProxy Redirector
// @namespace jtanx.plugins
// @description Automatically redirect to the proxified equivalent as provided by the University of Western Australia.
// @run-at document-start
// @grant none
// 
// @match http://repository.uwa.edu.au/*
// @match https://repository.uwa.edu.au/*
// @match http://cmo.library.uwa.edu.au/*
// @match https://cmo.library.uwa.edu.au/*
// @match http://cmo-devel.library.uwa.edu.au/*
// @match https://cmo-devel.library.uwa.edu.au/*
// @match http://my.uwa.edu.au/*
// @match https://my.uwa.edu.au/*
// @match http://uwa.eblib.com.au/*
// @match https://uwa.eblib.com.au/*
// @match http://www.australianmusiccentre.com.au/*
// @match https://www.australianmusiccentre.com.au/*
// @match http://vlearn.vea.com.au/*
// @match https://vlearn.vea.com.au/*
// @match http://forms.library.uwa.edu.au/*
// @match https://forms.library.uwa.edu.au/*
// @match http://theses.library.uwa.edu.au/*
// @match https://theses.library.uwa.edu.au/*
// @match http://static.library.uwa.edu.au/*
// @match https://static.library.uwa.edu.au/*
// @match http://www.aacrjournals.org/*
// @match https://www.aacrjournals.org/*
// @match http://www.aacr.org/*
// @match https://www.aacr.org/*
// @match http://www.aacrmeetingabstracts.org/*
// @match https://www.aacrmeetingabstracts.org/*
// @match http://aapgbulletin.datapages.com/*
// @match https://aapgbulletin.datapages.com/*
// @match http://search.ebscohost.com/*
// @match https://search.ebscohost.com/*
// @match http://ebooks.abc-clio.com/*
// @match https://ebooks.abc-clio.com/*
// @match http://accessengineeringlibrary.com/*
// @match https://accessengineeringlibrary.com/*
// @match http://accesspharmacy.mhmedical.com/*
// @match https://accesspharmacy.mhmedical.com/*
// @match http://portal.acm.org/*
// @match https://portal.acm.org/*
// @match https://dl.acm.org/*
// @match https://dl.acm.org/*
// @match http://pubs.acs.org/*
// @match https://pubs.acs.org/*
// @match http://acta.astrouw.edu.pl/*
// @match https://acta.astrouw.edu.pl/*
// @match http://www.actahort.org/*
// @match https://www.actahort.org/*
// @match http://www.actamathematica.org/*
// @match https://www.actamathematica.org/*
// @match http://www.acta.hu/*
// @match https://www.acta.hu/*
// @match http://app.pan.pl/*
// @match https://app.pan.pl/*
// @match http://www.architecture.com.au/*
// @match https://www.architecture.com.au/*
// @match http://www.ahajournals.org/*
// @match https://www.ahajournals.org/*
// @match http://www.aiaa.org/*
// @match https://www.aiaa.org/*
// @match http://aids-clinical-care.jwatch.org/*
// @match https://aids-clinical-care.jwatch.org/*
// @match http://www.humanitiesebook.org/*
// @match https://www.humanitiesebook.org/*
// @match http://search.alexanderstreet.com/*
// @match https://search.alexanderstreet.com/*
// @match http://www.akademiai.com/*
// @match https://www.akademiai.com/*
// @match http://www.astreetpress.com/*
// @match https://www.astreetpress.com/*
// @match http://ejournals.wspc.com.sg/*
// @match https://ejournals.wspc.com.sg/*
// @match http://neur.allenpress.com/*
// @match https://neur.allenpress.com/*
// @match http://intl.alphamedpress.org/*
// @match https://intl.alphamedpress.org/*
// @match http://www.aacc.org/*
// @match https://www.aacc.org/*
// @match http://www.aapm.org/*
// @match https://www.aapm.org/*
// @match http://jada.ada.org/*
// @match https://jada.ada.org/*
// @match http://www.aeaweb.org/*
// @match https://www.aeaweb.org/*
// @match http://www.agu.org/*
// @match https://www.agu.org/*
// @match http://intl.amjbot.org/*
// @match https://intl.amjbot.org/*
// @match http://www.ajcn.org/*
// @match https://www.ajcn.org/*
// @match http://www.ajhg.org/*
// @match https://www.ajhg.org/*
// @match http://www.amjpathol.org/*
// @match https://www.amjpathol.org/*
// @match http://ajp.press.uiuc.edu/*
// @match https://ajp.press.uiuc.edu/*
// @match http://www.ajsonline.org/*
// @match https://www.ajsonline.org/*
// @match http://www.ajtmh.org/*
// @match https://www.ajtmh.org/*
// @match http://www.ams.org/*
// @match https://www.ams.org/*
// @match http://www.minsocam.org/*
// @match https://www.minsocam.org/*
// @match http://*.aps.org/*
// @match https://*.aps.org/*
// @match http://www.physiology.org/*
// @match https://www.physiology.org/*
// @match http://www.the-aps.org/*
// @match https://www.the-aps.org/*
// @match http://www.amamanualofstyle.com/*
// @match https://www.amamanualofstyle.com/*
// @match http://alatechsource.metapress.com/*
// @match https://alatechsource.metapress.com/*
// @match http://alcts.metapress.com/*
// @match https://alcts.metapress.com/*
// @match http://journals.ametsoc.org/*
// @match https://journals.ametsoc.org/*
// @match http://www.agronomy.org/*
// @match https://www.agronomy.org/*
// @match http://www.ascb.org/*
// @match https://www.ascb.org/*
// @match http://www.asbmb.org/*
// @match https://www.asbmb.org/*
// @match http://ajcp.ascpjournals.org/*
// @match https://ajcp.ascpjournals.org/*
// @match http://horttech.ashspublications.org/*
// @match https://horttech.ashspublications.org/*
// @match http://www.hematology.org/*
// @match https://www.hematology.org/*
// @match http://jasn.asnjournals.org/*
// @match https://jasn.asnjournals.org/*
// @match http://www.asn-online.org/*
// @match https://www.asn-online.org/*
// @match http://www.atsjournals.org/*
// @match https://www.atsjournals.org/*
// @match http://www.annee-philologique.com/*
// @match https://www.annee-philologique.com/*
// @match http://www.anesthesiaprogress.org/*
// @match https://www.anesthesiaprogress.org/*
// @match http://www.annallergy.org/*
// @match https://www.annallergy.org/*
// @match http://www.annals.org/*
// @match https://www.annals.org/*
// @match http://annals.princeton.edu/*
// @match https://annals.princeton.edu/*
// @match http://www.theannals.com/*
// @match https://www.theannals.com/*
// @match http://www.annualreviews.org/*
// @match https://www.annualreviews.org/*
// @match http://www.imfareaer.org/*
// @match https://www.imfareaer.org/*
// @match http://www.anthrosource.net/*
// @match https://www.anthrosource.net/*
// @match http://antiquity.ac.uk/*
// @match https://antiquity.ac.uk/*
// @match http://content.apa.org/*
// @match https://content.apa.org/*
// @match http://www.adtmag.com/*
// @match https://www.adtmag.com/*
// @match http://apsjournals.apsnet.org/*
// @match https://apsjournals.apsnet.org/*
// @match http://www.artstor.org/*
// @match https://www.artstor.org/*
// @match http://www.ascelibrary.org/*
// @match https://www.ascelibrary.org/*
// @match http://www.asip.org/*
// @match https://www.asip.org/*
// @match http://www.aslo.org/*
// @match https://www.aslo.org/*
// @match http://products.asminternational.org/*
// @match https://products.asminternational.org/*
// @match http://www.asm.org/*
// @match https://www.asm.org/*
// @match http://elibrary.asabe.org/*
// @match https://elibrary.asabe.org/*
// @match http://www.asmedigitalcollection.asme.org/*
// @match https://www.asmedigitalcollection.asme.org/*
// @match http://www.aspectfinancial.com.au/*
// @match https://www.aspectfinancial.com.au/*
// @match http://www.aspetjournals.org/*
// @match https://www.aspetjournals.org/*
// @match http://www.asia-studies.com/*
// @match https://www.asia-studies.com/*
// @match http://www.afpe.org.uk/*
// @match https://www.afpe.org.uk/*
// @match http://crl.acrl.org/*
// @match https://crl.acrl.org/*
// @match http://journalsip.astm.org/*
// @match https://journalsip.astm.org/*
// @match http://enterprise.astm.org/*
// @match https://enterprise.astm.org/*
// @match http://www.oxford-auslawdictionary.com/*
// @match https://www.oxford-auslawdictionary.com/*
// @match http://www.austms.org.au/*
// @match https://www.austms.org.au/*
// @match http://www.onlinepublications.austroads.com.au/*
// @match https://www.onlinepublications.austroads.com.au/*
// @match http://www.abs.gov.au/*
// @match https://www.abs.gov.au/*
// @match http://www.austlit.edu.au/*
// @match https://www.austlit.edu.au/*
// @match http://www.asmjournals.org/*
// @match https://www.asmjournals.org/*
// @match http://eureka.rlg.org/*
// @match https://eureka.rlg.org/*
// @match http://journals.bcdecker.com/*
// @match https://journals.bcdecker.com/*
// @match http://www.bepress.com/*
// @match https://www.bepress.com/*
// @match http://www.waspress.co.uk/*
// @match https://www.waspress.co.uk/*
// @match http://www.begellhouse.com/*
// @match https://www.begellhouse.com/*
// @match http://ebooks.benthamscience.com/*
// @match https://ebooks.benthamscience.com/*
// @match http://bmc.lib.umich.edu/*
// @match https://bmc.lib.umich.edu/*
// @match http://apps.brepolis.net/*
// @match https://apps.brepolis.net/*
// @match http://autoweb.rlg.org/*
// @match https://autoweb.rlg.org/*
// @match http://www.biochemj.org/*
// @match https://www.biochemj.org/*
// @match http://bst.portlandpress.com/*
// @match https://bst.portlandpress.com/*
// @match http://www.biochemsoctrans.org/*
// @match https://www.biochemsoctrans.org/*
// @match http://www.biolbull.org/*
// @match https://www.biolbull.org/*
// @match http://www.biolreprod.org/*
// @match https://www.biolreprod.org/*
// @match http://www.biomedcentral.com/*
// @match https://www.biomedcentral.com/*
// @match http://ccforum.com/*
// @match https://ccforum.com/*
// @match http://alzres.com/*
// @match https://alzres.com/*
// @match http://arthritis-research.com/*
// @match https://arthritis-research.com/*
// @match http://breast-cancer-research.com/*
// @match https://breast-cancer-research.com/*
// @match http://genomebiology.com/*
// @match https://genomebiology.com/*
// @match http://genomemedicine.com/*
// @match https://genomemedicine.com/*
// @match http://stemcellres.com/*
// @match https://stemcellres.com/*
// @match http://www.biophysj.org/*
// @match https://www.biophysj.org/*
// @match http://www.sociologyencyclopedia.com/*
// @match https://www.sociologyencyclopedia.com/*
// @match http://www.blackwellreference.com/*
// @match https://www.blackwellreference.com/*
// @match http://www.blackwell-synergy.com/*
// @match https://www.blackwell-synergy.com/*
// @match http://www.bloodjournal.org/*
// @match https://www.bloodjournal.org/*
// @match http://www.bioscientifica.com/*
// @match https://www.bioscientifica.com/*
// @match http://dmfr.birjournals.org/*
// @match https://dmfr.birjournals.org/*
// @match http://journals.bmj.com/*
// @match https://journals.bmj.com/*
// @match http://journals.brepols.net/*
// @match https://journals.brepols.net/*
// @match http://brepols.metapress.com/*
// @match https://brepols.metapress.com/*
// @match http://www.bridgemaneducation.com/*
// @match https://www.bridgemaneducation.com/*
// @match http://referenceworks.brillonline.com/*
// @match https://referenceworks.brillonline.com/*
// @match http://www.brillonline.nl/*
// @match https://www.brillonline.nl/*
// @match http://nijhoffonline.nl/*
// @match https://nijhoffonline.nl/*
// @match http://britishacademy.universitypressscholarship.com/*
// @match https://britishacademy.universitypressscholarship.com/*
// @match http://bjp.rcpsych.org/*
// @match https://bjp.rcpsych.org/*
// @match http://britishperiodicals.chadwyck.co.uk/*
// @match https://britishperiodicals.chadwyck.co.uk/*
// @match http://www.pharmacopoeia.co.uk/*
// @match https://www.pharmacopoeia.co.uk/*
// @match http://www.abcb.gov.au/*
// @match https://www.abcb.gov.au/*
// @match http://www.bcaillustrated.com.au/*
// @match https://www.bcaillustrated.com.au/*
// @match http://www.businessnews.com.au/*
// @match https://www.businessnews.com.au/*
// @match http://bww.dnb.com.au/*
// @match https://bww.dnb.com.au/*
// @match http://www.butterworthsonline.com/*
// @match https://www.butterworthsonline.com/*
// @match http://www.cabdirect.org/*
// @match https://www.cabdirect.org/*
// @match http://www.cabi.org/*
// @match https://www.cabi.org/*
// @match http://caliber.ucpress.net/*
// @match https://caliber.ucpress.net/*
// @match http://histories.cambridge.org/*
// @match https://histories.cambridge.org/*
// @match http://universitypublishingonline.org/*
// @match https://universitypublishingonline.org/*
// @match http://journals.cambridge.org/*
// @match https://journals.cambridge.org/*
// @match http://uwa.cambridge.patron.eb20.com/*
// @match https://uwa.cambridge.patron.eb20.com/*
// @match http://www.csa3.com/*
// @match https://www.csa3.com/*
// @match http://www.caaa.ca/*
// @match https://www.caaa.ca/*
// @match http://journals.cms.math.ca/*
// @match https://journals.cms.math.ca/*
// @match http://www.cmaj.ca/*
// @match https://www.cmaj.ca/*
// @match http://www.canmin.org/*
// @match https://www.canmin.org/*
// @match http://pubservices.nrc-cnrc.ca/*
// @match https://pubservices.nrc-cnrc.ca/*
// @match http://www.lexxion.eu/*
// @match https://www.lexxion.eu/*
// @match http://ww3.cch.com.au:8080/*
// @match https://ww3.cch.com.au:8080/*
// @match http://www.ceda.com.au/*
// @match https://www.ceda.com.au/*
// @match http://www.cellbiolint.org/*
// @match https://www.cellbiolint.org/*
// @match http://www.cellpress.com/*
// @match https://www.cellpress.com/*
// @match http://eebo.chadwyck.com/*
// @match https://eebo.chadwyck.com/*
// @match http://iimp.chadwyck.com/*
// @match https://iimp.chadwyck.com/*
// @match http://iimpft.chadwyck.com/*
// @match https://iimpft.chadwyck.com/*
// @match http://www.charlestonco.com/*
// @match https://www.charlestonco.com/*
// @match http://www.chelonianjournals.org/*
// @match https://www.chelonianjournals.org/*
// @match http://www.csj.jp/*
// @match https://www.csj.jp/*
// @match http://www.chemnetbase.com/*
// @match https://www.chemnetbase.com/*
// @match http://www.chicagomanualofstyle.org/*
// @match https://www.chicagomanualofstyle.org/*
// @match http://oversea.cnki.net/*
// @match https://oversea.cnki.net/*
// @match http://www.pkulaw.cn/*
// @match https://www.pkulaw.cn/*
// @match http://www.cefc.com.hk/*
// @match https://www.cefc.com.hk/*
// @match http://www.cro3.org/*
// @match https://www.cro3.org/*
// @match http://www.citiprogram.org/*
// @match https://www.citiprogram.org/*
// @match http://shmu.alexanderstreet.com/*
// @match https://shmu.alexanderstreet.com/*
// @match http://www.classiques-garnier.com/*
// @match https://www.classiques-garnier.com/*
// @match http://uwau.classical.com/*
// @match https://uwau.classical.com/*
// @match http://www.aspresolver.com/*
// @match https://www.aspresolver.com/*
// @match http://www.clinchem.org/*
// @match https://www.clinchem.org/*
// @match http://clinicalevidence.bmj.com/*
// @match https://clinicalevidence.bmj.com/*
// @match http://www.clinicalkey.com/*
// @match https://www.clinicalkey.com/*
// @match http://www.clinicalevidence.org/*
// @match https://www.clinicalevidence.org/*
// @match http://cs.portlandpress.com/*
// @match https://cs.portlandpress.com/*
// @match http://www.update-software.com/*
// @match https://www.update-software.com/*
// @match http://cognet.mit.edu/*
// @match https://cognet.mit.edu/*
// @match http://www.comlaw.gov.au/*
// @match https://www.comlaw.gov.au/*
// @match http://www.biologists.org/*
// @match https://www.biologists.org/*
// @match http://www.biologists.com/*
// @match https://www.biologists.com/*
// @match http://www.computerworld.com.au/*
// @match https://www.computerworld.com.au/*
// @match http://www.connect4.com.au/*
// @match https://www.connect4.com.au/*
// @match http://www.connectweb.com.au/*
// @match https://www.connectweb.com.au/*
// @match http://www.oceanalaw.com/*
// @match https://www.oceanalaw.com/*
// @match http://www.asihcopeiaonline.org/*
// @match https://www.asihcopeiaonline.org/*
// @match http://www.cortex-online.org/*
// @match https://www.cortex-online.org/*
// @match http://library.cqpress.com/*
// @match https://library.cqpress.com/*
// @match http://www.crcnetbase.com/*
// @match https://www.crcnetbase.com/*
// @match http://www.credoreference.com/*
// @match https://www.credoreference.com/*
// @match http://www.edata-center.com/*
// @match https://www.edata-center.com/*
// @match http://dx.doi.org/*
// @match https://dx.doi.org/*
// @match http://www.publish.csiro.au/*
// @match https://www.publish.csiro.au/*
// @match http://clp.oxfordjournals.org/*
// @match https://clp.oxfordjournals.org/*
// @match http://web.ovid.unilinc.edu.au/*
// @match https://web.ovid.unilinc.edu.au/*
// @match http://www.current-reports.com/*
// @match https://www.current-reports.com/*
// @match http://www.datatrace.com/*
// @match https://www.datatrace.com/*
// @match http://www.datamonitor.com/*
// @match https://www.datamonitor.com/*
// @match http://www.dbpia.co.kr/*
// @match https://www.dbpia.co.kr/*
// @match http://www.datagold.com/*
// @match https://www.datagold.com/*
// @match http://www.gender.amdigital.co.uk/*
// @match https://www.gender.amdigital.co.uk/*
// @match http://www.dental-update.co.uk/*
// @match https://www.dental-update.co.uk/*
// @match http://www.dialogatsite.com/*
// @match https://www.dialogatsite.com/*
// @match http://dib.cambridge.org/*
// @match https://dib.cambridge.org/*
// @match http://www.dukeupress.edu/*
// @match https://www.dukeupress.edu/*
// @match http://www.dukejournals.org/*
// @match https://www.dukejournals.org/*
// @match http://www.dukemathjournal.org/*
// @match https://www.dukemathjournal.org/*
// @match http://www.earthmagazine.org/*
// @match https://www.earthmagazine.org/*
// @match http://www.exacteditions.com/*
// @match https://www.exacteditions.com/*
// @match http://www.esajournals.org/*
// @match https://www.esajournals.org/*
// @match http://www.edpsciences.org/*
// @match https://www.edpsciences.org/*
// @match http://www.europhysicsnews.org/*
// @match https://www.europhysicsnews.org/*
// @match http://www.aanda.org/*
// @match https://www.aanda.org/*
// @match http://www.euppublishing.com/*
// @match https://www.euppublishing.com/*
// @match http://www.editlib.org/*
// @match https://www.editlib.org/*
// @match http://www.educause.edu/*
// @match https://www.educause.edu/*
// @match http://www.elgaronline.com/*
// @match https://www.elgaronline.com/*
// @match http://www.electrochem.org/*
// @match https://www.electrochem.org/*
// @match http://ecsdl.org/*
// @match https://ecsdl.org/*
// @match http://www.e-enlightenment.com/*
// @match https://www.e-enlightenment.com/*
// @match http://www.expertconsultbook.com/*
// @match https://www.expertconsultbook.com/*
// @match http://www.emeraldinsight.com/*
// @match https://www.emeraldinsight.com/*
// @match http://www.empire.amdigital.co.uk/*
// @match https://www.empire.amdigital.co.uk/*
// @match http://www.igi-online.com/*
// @match https://www.igi-online.com/*
// @match http://www.oxford-naswsocialwork.com/*
// @match https://www.oxford-naswsocialwork.com/*
// @match http://press.endocrine.org/*
// @match https://press.endocrine.org/*
// @match http://www.engineeringvillage.com/*
// @match https://www.engineeringvillage.com/*
// @match http://www.justis.com/*
// @match https://www.justis.com/*
// @match http://www.engnetbase.com/*
// @match https://www.engnetbase.com/*
// @match http://edition.pagesuite-professional.co.uk/*
// @match https://edition.pagesuite-professional.co.uk/*
// @match http://www.envplan.com/*
// @match https://www.envplan.com/*
// @match http://www.yale.edu/*
// @match https://www.yale.edu/*
// @match http://www.eolss.net/*
// @match https://www.eolss.net/*
// @match http://www.equinoxpub.com/*
// @match https://www.equinoxpub.com/*
// @match http://hwwilsonweb.com/*
// @match https://hwwilsonweb.com/*
// @match http://vnweb.hwwilsonweb.com/*
// @match https://vnweb.hwwilsonweb.com/*
// @match http://www.edrs.com/*
// @match https://www.edrs.com/*
// @match http://estuariesandcoasts.org/*
// @match https://estuariesandcoasts.org/*
// @match http://etg.tg.com.au/*
// @match https://etg.tg.com.au/*
// @match http://www.erudit.org/*
// @match https://www.erudit.org/*
// @match http://www.europaworld.com/*
// @match https://www.europaworld.com/*
// @match http://www.eje-online.org/*
// @match https://www.eje-online.org/*
// @match http://www.ems-ph.org/*
// @match https://www.ems-ph.org/*
// @match http://www.erj.ersjournals.com/*
// @match https://www.erj.ersjournals.com/*
// @match http://www.evolutionary-ecology.com/*
// @match https://www.evolutionary-ecology.com/*
// @match http://www.ebmonline.org/*
// @match https://www.ebmonline.org/*
// @match http://www.digitaleditions.com.au/*
// @match https://www.digitaleditions.com.au/*
// @match http://www.libraryedition.com.au/*
// @match https://www.libraryedition.com.au/*
// @match http://f1000.com/*
// @match https://f1000.com/*
// @match http://www.fasebj.org/*
// @match https://www.fasebj.org/*
// @match http://www.fq.math.ca/*
// @match https://www.fq.math.ca/*
// @match http://infotrac.galegroup.com/*
// @match https://infotrac.galegroup.com/*
// @match http://www.finsia.com/*
// @match https://www.finsia.com/*
// @match http://www.fupress.net/*
// @match https://www.fupress.net/*
// @match http://flm-journal.org/*
// @match https://flm-journal.org/*
// @match http://fordham.universitypressscholarship.com/*
// @match https://fordham.universitypressscholarship.com/*
// @match http://www.atilf.fr/*
// @match https://www.atilf.fr/*
// @match http://www.futuremedicine.com/*
// @match https://www.futuremedicine.com/*
// @match http://find.galegroup.com/*
// @match https://find.galegroup.com/*
// @match http://www.gendatabaseonline.com/*
// @match https://www.gendatabaseonline.com/*
// @match http://genesdev.cshlp.org/*
// @match https://genesdev.cshlp.org/*
// @match http://www.genetics.org/*
// @match https://www.genetics.org/*
// @match http://www.geoscienceworld.org/*
// @match https://www.geoscienceworld.org/*
// @match http://www.csa.com/*
// @match https://www.csa.com/*
// @match http://www.icevirtuallibrary.com/*
// @match https://www.icevirtuallibrary.com/*
// @match http://GIDEONonline.net/*
// @match https://GIDEONonline.net/*
// @match http://www.portal.euromonitor.com/*
// @match https://www.portal.euromonitor.com/*
// @match http://www3.griffith.edu.au/*
// @match https://www3.griffith.edu.au/*
// @match http://ebooks.greenwood.com/*
// @match https://ebooks.greenwood.com/*
// @match http://www.groundimprovement.com/*
// @match https://www.groundimprovement.com/*
// @match http://guilfordjournals.com/*
// @match https://guilfordjournals.com/*
// @match http://www.hbcpnetbase.com/*
// @match https://www.hbcpnetbase.com/*
// @match http://www.accessmedicine.com/*
// @match https://www.accessmedicine.com/*
// @match http://www.hartjournals.co.uk/*
// @match https://www.hartjournals.co.uk/*
// @match http://www.hhpr.org/*
// @match https://www.hhpr.org/*
// @match http://ebooks.hcn.com.au/*
// @match https://ebooks.hcn.com.au/*
// @match http://heinonline.org/*
// @match https://heinonline.org/*
// @match http://henrystewart.metapress.com/*
// @match https://henrystewart.metapress.com/*
// @match http://www.hstalks.com/*
// @match https://www.hstalks.com/*
// @match http://www.hljournals.org/*
// @match https://www.hljournals.org/*
// @match http://www.heterocycles.jp/*
// @match https://www.heterocycles.jp/*
// @match http://highwire.stanford.edu/*
// @match https://highwire.stanford.edu/*
// @match http://www.hh.um.es/*
// @match https://www.hh.um.es/*
// @match http://historicbrass.org/*
// @match https://historicbrass.org/*
// @match http://serials.abc-clio.com/*
// @match https://serials.abc-clio.com/*
// @match http://www.math.uh.edu/*
// @match https://www.math.uh.edu/*
// @match http://parlipapers.chadwyck.co.uk/*
// @match https://parlipapers.chadwyck.co.uk/*
// @match http://clients.ibisworld.com.au/*
// @match https://clients.ibisworld.com.au/*
// @match http://ieeexplore.ieee.org/*
// @match https://ieeexplore.ieee.org/*
// @match http://books.igi-online.com/*
// @match https://books.igi-online.com/*
// @match http://services.igi-global.com/*
// @match https://services.igi-global.com/*
// @match http://portal.igpublish.com/*
// @match https://portal.igpublish.com/*
// @match http://www.iias.nl/*
// @match https://www.iias.nl/*
// @match http://old.iias.asia/*
// @match https://old.iias.asia/*
// @match http://www.cababstractsplus.org/*
// @match https://www.cababstractsplus.org/*
// @match http://incites.isiknowledge.com/*
// @match https://incites.isiknowledge.com/*
// @match http://www.inderscienceonline.com/*
// @match https://www.inderscienceonline.com/*
// @match http://www.indiaraj.amdigital.co.uk/*
// @match https://www.indiaraj.amdigital.co.uk/*
// @match http://www.iumj.indiana.edu/*
// @match https://www.iumj.indiana.edu/*
// @match http://cip.cornell.edu/*
// @match https://cip.cornell.edu/*
// @match http://iai.asm.org/*
// @match https://iai.asm.org/*
// @match http://www.infosci-books.com/*
// @match https://www.infosci-books.com/*
// @match http://journals.informs.org/*
// @match https://journals.informs.org/*
// @match http://www.informaworld.com/*
// @match https://www.informaworld.com/*
// @match http://www.informahealthcare.com/*
// @match https://www.informahealthcare.com/*
// @match http://www.i-law.com/*
// @match https://www.i-law.com/*
// @match http://search.informit.com.au/*
// @match https://search.informit.com.au/*
// @match http://www.ingentaconnect.com/*
// @match https://www.ingentaconnect.com/*
// @match http://www.ingentaselect.com/*
// @match https://www.ingentaselect.com/*
// @match http://icsd.fiz-karlsruhe.de/*
// @match https://icsd.fiz-karlsruhe.de/*
// @match http://www.iijournals.com/*
// @match https://www.iijournals.com/*
// @match http://intelliconnect.wkasiapacific.com/*
// @match https://intelliconnect.wkasiapacific.com/*
// @match http://www.aaiddjournals.org/*
// @match https://www.aaiddjournals.org/*
// @match http://www.ijdb.ehu.es/*
// @match https://www.ijdb.ehu.es/*
// @match http://www.communicationencyclopedia.com/*
// @match https://www.communicationencyclopedia.com/*
// @match http://www.ijocs.org/*
// @match https://www.ijocs.org/*
// @match http://www.ijee.dit.ie/*
// @match https://www.ijee.dit.ie/*
// @match http://www.intmedpress.com/*
// @match https://www.intmedpress.com/*
// @match http://www.brepolis.net/*
// @match https://www.brepolis.net/*
// @match http://www.imf.org/*
// @match https://www.imf.org/*
// @match http://www.imfstatistics.org/*
// @match https://www.imfstatistics.org/*
// @match http://www.intlpress.com/*
// @match https://www.intlpress.com/*
// @match http://journals.iucr.org/*
// @match https://journals.iucr.org/*
// @match http://intarch.ac.uk/*
// @match https://intarch.ac.uk/*
// @match http://onlinelibrary.wiley.com/*
// @match https://onlinelibrary.wiley.com/*
// @match http://intl.iovs.org/*
// @match https://intl.iovs.org/*
// @match http://oxia.ouplaw.com/*
// @match https://oxia.ouplaw.com/*
// @match http://www.iop.org/*
// @match https://www.iop.org/*
// @match http://content.iospress.com/*
// @match https://content.iospress.com/*
// @match http://webofknowledge.com/*
// @match https://webofknowledge.com/*
// @match http://apps.webofknowledge.com/*
// @match https://apps.webofknowledge.com/*
// @match http://www.webofknowledge.com/*
// @match https://www.webofknowledge.com/*
// @match http://www.researcherid.com/*
// @match https://www.researcherid.com/*
// @match http://www.ipasource.com/*
// @match https://www.ipasource.com/*
// @match http://www.ishib.org/*
// @match https://www.ishib.org/*
// @match http://www.sif.it/*
// @match https://www.sif.it/*
// @match http://www.itergateway.org/*
// @match https://www.itergateway.org/*
// @match http://www.iwaponline.com/*
// @match https://www.iwaponline.com/*
// @match http://www.jstage.jst.go.jp/*
// @match https://www.jstage.jst.go.jp/*
// @match http://www.joannabriggs.edu.au/*
// @match https://www.joannabriggs.edu.au/*
// @match http://connect.jbiconnectplus.org/*
// @match https://connect.jbiconnectplus.org/*
// @match http://jid.sagepub.com/*
// @match https://jid.sagepub.com/*
// @match http://www.lyellcollection.org/*
// @match https://www.lyellcollection.org/*
// @match http://www.asadl.org/*
// @match https://www.asadl.org/*
// @match http://www.african-archaeology.de/*
// @match https://www.african-archaeology.de/*
// @match http://agdevjournal.com/*
// @match https://agdevjournal.com/*
// @match http://www.jabfp.org/*
// @match https://www.jabfp.org/*
// @match http://www.japmaonline.org/*
// @match https://www.japmaonline.org/*
// @match http://www.journalofanimalscience.org/*
// @match https://www.journalofanimalscience.org/*
// @match http://quod.lib.umich.edu/*
// @match https://quod.lib.umich.edu/*
// @match http://www.sloan-c.org/*
// @match https://www.sloan-c.org/*
// @match http://intl.jbc.org/*
// @match https://intl.jbc.org/*
// @match http://www.ejbjs.org/*
// @match https://www.ejbjs.org/*
// @match http://www.jbmronline.com/*
// @match https://www.jbmronline.com/*
// @match http://jchemed.chem.wisc.edu/*
// @match https://jchemed.chem.wisc.edu/*
// @match http://jco.ascopubs.org/*
// @match https://jco.ascopubs.org/*
// @match http://www.psychiatrist.com/*
// @match https://www.psychiatrist.com/*
// @match http://jds.fass.org/*
// @match https://jds.fass.org/*
// @match http://www.jdentaled.org/*
// @match https://www.jdentaled.org/*
// @match http://gerontologist.gerontologyjournals.org/*
// @match https://gerontologist.gerontologyjournals.org/*
// @match http://www.iaglr.org/*
// @match https://www.iaglr.org/*
// @match http://www.journalofgreenbuilding.com/*
// @match https://www.journalofgreenbuilding.com/*
// @match http://www.jhortscib.org/*
// @match https://www.jhortscib.org/*
// @match http://www.jimmunol.org/*
// @match https://www.jimmunol.org/*
// @match http://www.jleukbio.org/*
// @match https://www.jleukbio.org/*
// @match http://www.jlr.org/*
// @match https://www.jlr.org/*
// @match http://www.jomms.org/*
// @match https://www.jomms.org/*
// @match http://www.jmecology.com/*
// @match https://www.jmecology.com/*
// @match http://jmd.amjpathol.org/*
// @match https://jmd.amjpathol.org/*
// @match http://www.jnrlse.org/*
// @match https://www.jnrlse.org/*
// @match http://www.jneurosci.org/*
// @match https://www.jneurosci.org/*
// @match http://www-thejns-net.org/*
// @match https://www-thejns-net.org/*
// @match http://www.jnabs.org/*
// @match https://www.jnabs.org/*
// @match http://jn.nutrition.org/*
// @match https://jn.nutrition.org/*
// @match http://jorthod.maneyjournals.org/*
// @match https://jorthod.maneyjournals.org/*
// @match http://www.jospt.org/*
// @match https://www.jospt.org/*
// @match http://www.journalofphilosophy.org/*
// @match https://www.journalofphilosophy.org/*
// @match http://www.joponline.org/*
// @match https://www.joponline.org/*
// @match http://jrm.medicaljournals.se/*
// @match https://jrm.medicaljournals.se/*
// @match http://www.jrheum.com/*
// @match https://www.jrheum.com/*
// @match http://www.jrheum.org/*
// @match https://www.jrheum.org/*
// @match http://journals.asha.org/*
// @match https://journals.asha.org/*
// @match http://www.jsad.com/*
// @match https://www.jsad.com/*
// @match http://www.jultrasoundmed.org/*
// @match https://www.jultrasoundmed.org/*
// @match http://www.jove.com/*
// @match https://www.jove.com/*
// @match http://www.opuluspress.se/*
// @match https://www.opuluspress.se/*
// @match http://www.jstor.org/*
// @match https://www.jstor.org/*
// @match http://plants.jstor.org/*
// @match https://plants.jstor.org/*
// @match http://www.justcite.com/*
// @match https://www.justcite.com/*
// @match http://uwa.kanopystreaming.com/*
// @match https://uwa.kanopystreaming.com/*
// @match http://www.karger.com/*
// @match https://www.karger.com/*
// @match http://content.karger.com/*
// @match https://content.karger.com/*
// @match http://www.rbgkew.org.uk/*
// @match https://www.rbgkew.org.uk/*
// @match http://klapp-online.de/*
// @match https://klapp-online.de/*
// @match http://www.kluwerarbitration.com/*
// @match https://www.kluwerarbitration.com/*
// @match http://www.kluweronline.com/*
// @match https://www.kluweronline.com/*
// @match http://www.kluwerlawonline.com/*
// @match https://www.kluwerlawonline.com/*
// @match http://www.knovel.com/*
// @match https://www.knovel.com/*
// @match http://www.labanimal.com/*
// @match https://www.labanimal.com/*
// @match http://www.thelancet.com/*
// @match https://www.thelancet.com/*
// @match http://www.revues.armand-colin.com/*
// @match https://www.revues.armand-colin.com/*
// @match http://tla.thomson.com.au/*
// @match https://tla.thomson.com.au/*
// @match http://subscriber.lawbookco.com.au/*
// @match https://subscriber.lawbookco.com.au/*
// @match http://www.lcoastpress.com/*
// @match https://www.lcoastpress.com/*
// @match http://my.lawlex.com.au/*
// @match https://my.lawlex.com.au/*
// @match http://llama.metapress.com/*
// @match https://llama.metapress.com/*
// @match http://librarymusicsource.com/*
// @match https://librarymusicsource.com/*
// @match http://leme.library.utoronto.ca/*
// @match https://leme.library.utoronto.ca/*
// @match http://www.lexisnexis.com.au/*
// @match https://www.lexisnexis.com.au/*
// @match http://librariesaustralia.nla.gov.au/*
// @match https://librariesaustralia.nla.gov.au/*
// @match http://online.liebertpub.com/*
// @match https://online.liebertpub.com/*
// @match http://www.litencyc.com/*
// @match https://www.litencyc.com/*
// @match http://www.literatureencyclopedia.com/*
// @match https://www.literatureencyclopedia.com/*
// @match http://lion.chadwyck.co.uk/*
// @match https://lion.chadwyck.co.uk/*
// @match http://www.londonlowlife.amdigital.co.uk/*
// @match https://www.londonlowlife.amdigital.co.uk/*
// @match http://www.lrb.co.uk/*
// @match https://www.lrb.co.uk/*
// @match http://lupjournals.org/*
// @match https://lupjournals.org/*
// @match http://www.macquariedictionary.com.au/*
// @match https://www.macquariedictionary.com.au/*
// @match http://www.maneyonline.com/*
// @match https://www.maneyonline.com/*
// @match http://www.mrlonline.org/*
// @match https://www.mrlonline.org/*
// @match http://msp.org/*
// @match https://msp.org/*
// @match http://www.mathscipub.org/*
// @match https://www.mathscipub.org/*
// @match http://www.mathnetbase.com/*
// @match https://www.mathnetbase.com/*
// @match http://opil.ouplaw.com/*
// @match https://opil.ouplaw.com/*
// @match http://online.medphys.org/*
// @match https://online.medphys.org/*
// @match http://www.mja.com.au/*
// @match https://www.mja.com.au/*
// @match http://www.medicalevidencematters.com/*
// @match https://www.medicalevidencematters.com/*
// @match http://www.medici.tv/*
// @match https://www.medici.tv/*
// @match http://www.medicinescomplete.com/*
// @match https://www.medicinescomplete.com/*
// @match http://www.mergentonline.com/*
// @match https://www.mergentonline.com/*
// @match http://www.metapress.com/*
// @match https://www.metapress.com/*
// @match http://www.sanbi.co.jp/*
// @match https://www.sanbi.co.jp/*
// @match http://www.micromedexsolutions.com/*
// @match https://www.micromedexsolutions.com/*
// @match http://search.micronexx.com/*
// @match https://search.micronexx.com/*
// @match http://www.mimsonline.com.au/*
// @match https://www.mimsonline.com.au/*
// @match http://www.mitpressjournals.org/*
// @match https://www.mitpressjournals.org/*
// @match http://collections.chadwyck.co.uk/*
// @match https://collections.chadwyck.co.uk/*
// @match http://www.mlajournals.org/*
// @match https://www.mlajournals.org/*
// @match http://publications.epress.monash.edu/*
// @match https://publications.epress.monash.edu/*
// @match http://www.mcponline.org/*
// @match https://www.mcponline.org/*
// @match http://epress.monash.edu/*
// @match https://epress.monash.edu/*
// @match http://publishing.monash.edu/*
// @match https://publishing.monash.edu/*
// @match http://www.morganclaypool.com/*
// @match https://www.morganclaypool.com/*
// @match http://datanalysis.morningstar.com.au/*
// @match https://datanalysis.morningstar.com.au/*
// @match http://multi-science.metapress.com/*
// @match https://multi-science.metapress.com/*
// @match http://jmpt.hcn.com.au/*
// @match https://jmpt.hcn.com.au/*
// @match http://www.msa.org.au/*
// @match https://www.msa.org.au/*
// @match http://www.musicforum.org.au/*
// @match https://www.musicforum.org.au/*
// @match http://muco.alexanderstreet.com/*
// @match https://muco.alexanderstreet.com/*
// @match http://www.myilibrary.com/*
// @match https://www.myilibrary.com/*
// @match http://myrmecologicalnews.org/*
// @match https://myrmecologicalnews.org/*
// @match http://periodicals.narr.de/*
// @match https://periodicals.narr.de/*
// @match http://www.nature.com/*
// @match https://www.nature.com/*
// @match http://uwa.naxosvideolibrary.com/*
// @match https://uwa.naxosvideolibrary.com/*
// @match http://uwa.naxosmusiclibrary.com/*
// @match https://uwa.naxosmusiclibrary.com/*
// @match http://www.nber.org/*
// @match https://www.nber.org/*
// @match http://nearmap.com/*
// @match https://nearmap.com/*
// @match http://www.neilsonjournals.com/*
// @match https://www.neilsonjournals.com/*
// @match http://neoreviews.aappublications.org/*
// @match https://neoreviews.aappublications.org/*
// @match http://www.nejm.org/*
// @match https://www.nejm.org/*
// @match http://nejm.highwire.org/*
// @match https://nejm.highwire.org/*
// @match http://www.newleftreview.org/*
// @match https://www.newleftreview.org/*
// @match http://www.dictionaryofeconomics.com/*
// @match https://www.dictionaryofeconomics.com/*
// @match http://www.nybooks.com/*
// @match https://www.nybooks.com/*
// @match http://www.pacificarchaeology.org/*
// @match https://www.pacificarchaeology.org/*
// @match http://journal.nzma.org.nz/*
// @match https://journal.nzma.org.nz/*
// @match http://c19.chadwyck.co.uk/*
// @match https://c19.chadwyck.co.uk/*
// @match http://www.nowpublishers.com/*
// @match https://www.nowpublishers.com/*
// @match http://www.nrcresearchpress.com/*
// @match https://www.nrcresearchpress.com/*
// @match http://mcom.alexanderstreet.com/*
// @match https://mcom.alexanderstreet.com/*
// @match http://www.nursingreview.com.au/*
// @match https://www.nursingreview.com.au/*
// @match http://www.statistics.gov.uk/*
// @match https://www.statistics.gov.uk/*
// @match http://ojps.aip.org/*
// @match https://ojps.aip.org/*
// @match http://www.oldenbourg-link.com/*
// @match https://www.oldenbourg-link.com/*
// @match http://www.onarchitecture.com/*
// @match https://www.onarchitecture.com/*
// @match http://www.mathjournals.org/*
// @match https://www.mathjournals.org/*
// @match http://www.onemine.org/*
// @match https://www.onemine.org/*
// @match http://www.openbookpublishers.com/*
// @match https://www.openbookpublishers.com/*
// @match http://www.jopdentonline.org/*
// @match https://www.jopdentonline.org/*
// @match http://www.opticsinfobase.org/*
// @match https://www.opticsinfobase.org/*
// @match http://www.orchestralmusic.com/*
// @match https://www.orchestralmusic.com/*
// @match http://ovidsp.ovid.com/*
// @match https://ovidsp.ovid.com/*
// @match http://somme.library.uwa.edu.au/*
// @match https://somme.library.uwa.edu.au/*
// @match http://www.oldcitypublishing.com/*
// @match https://www.oldcitypublishing.com/*
// @match http://www.atypon-link.com/*
// @match https://www.atypon-link.com/*
// @match http://access.ovid.com/*
// @match https://access.ovid.com/*
// @match http://online.factsandcomparisons.com/*
// @match https://online.factsandcomparisons.com/*
// @match http://advisor.lww.com/*
// @match https://advisor.lww.com/*
// @match http://www.oxfordartonline.com/*
// @match https://www.oxfordartonline.com/*
// @match http://www.oxfordbibliographies.com/*
// @match https://www.oxfordbibliographies.com/*
// @match http://www.oxforddnb.com/*
// @match https://www.oxforddnb.com/*
// @match http://www.oxford-humanrights.com/*
// @match https://www.oxford-humanrights.com/*
// @match http://www.oxford-economichistory.com/*
// @match https://www.oxford-economichistory.com/*
// @match http://www.oxford-theatreandperformance.com/*
// @match https://www.oxford-theatreandperformance.com/*
// @match http://www.oxfordhandbooks.com/*
// @match https://www.oxfordhandbooks.com/*
// @match http://www.oxfordwesternmusic.com/*
// @match https://www.oxfordwesternmusic.com/*
// @match http://acn.oxfordjournals.org/*
// @match https://acn.oxfordjournals.org/*
// @match http://www.oed.com/*
// @match https://www.oed.com/*
// @match http://www.oxfordjournals.org/*
// @match https://www.oxfordjournals.org/*
// @match http://jwelb.oxfordjournals.org/*
// @match https://jwelb.oxfordjournals.org/*
// @match http://www.oxfordmusiconline.com/*
// @match https://www.oxfordmusiconline.com/*
// @match http://www.oxfordreference.com/*
// @match https://www.oxfordreference.com/*
// @match http://www.oxfordscholarship.com/*
// @match https://www.oxfordscholarship.com/*
// @match http://pjm.math.berkeley.edu/*
// @match https://pjm.math.berkeley.edu/*
// @match http://www.museumoftheearth.org/*
// @match https://www.museumoftheearth.org/*
// @match http://www.palgrave-journals.com/*
// @match https://www.palgrave-journals.com/*
// @match http://geo.arizona.edu/*
// @match https://geo.arizona.edu/*
// @match http://pediatrics.aappublications.org/*
// @match https://pediatrics.aappublications.org/*
// @match http://poj.peeters-leuven.be/*
// @match https://poj.peeters-leuven.be/*
// @match http://www.perceptionweb.com/*
// @match https://www.perceptionweb.com/*
// @match http://pci.chadwyck.com/*
// @match https://pci.chadwyck.com/*
// @match http://pio.chadwyck.co.uk/*
// @match https://pio.chadwyck.co.uk/*
// @match http://pao.chadwyck.co.uk/*
// @match https://pao.chadwyck.co.uk/*
// @match http://www.kappanmagazine.org/*
// @match https://www.kappanmagazine.org/*
// @match http://www.pdcnet.org/*
// @match https://www.pdcnet.org/*
// @match http://thephilosophersmagazine.com/*
// @match https://thephilosophersmagazine.com/*
// @match http://philpapers.org/*
// @match https://philpapers.org/*
// @match http://www.phycologia.org/*
// @match https://www.phycologia.org/*
// @match http://physicsworldarchive.iop.org/*
// @match https://physicsworldarchive.iop.org/*
// @match http://www.physsportsmed.com/*
// @match https://www.physsportsmed.com/*
// @match http://piprofiler.systematics.net.au/*
// @match https://piprofiler.systematics.net.au/*
// @match http://www.pidgeondigital.com/*
// @match https://www.pidgeondigital.com/*
// @match http://www.plantcell.org/*
// @match https://www.plantcell.org/*
// @match http://www.plantphysiol.org/*
// @match https://www.plantphysiol.org/*
// @match http://www.polymersdatabase.com/*
// @match https://www.polymersdatabase.com/*
// @match http://dlib.eastview.com/*
// @match https://dlib.eastview.com/*
// @match http://ps.fass.org/*
// @match https://ps.fass.org/*
// @match http://www.pnas.org/*
// @match https://www.pnas.org/*
// @match http://www.sciquest.org.nz/*
// @match https://www.sciquest.org.nz/*
// @match http://www.presidian.com.au/*
// @match https://www.presidian.com.au/*
// @match http://library.pressdisplay.com/*
// @match https://library.pressdisplay.com/*
// @match http://www.sleepmedtext.com/*
// @match https://www.sleepmedtext.com/*
// @match http://projecteuclid.org/*
// @match https://projecteuclid.org/*
// @match http://muse.jhu.edu.au/*
// @match https://muse.jhu.edu.au/*
// @match http://search.proquest.com/*
// @match https://search.proquest.com/*
// @match http://www.proteinscience.org/*
// @match https://www.proteinscience.org/*
// @match http://www.psychiatryonline.org/*
// @match https://www.psychiatryonline.org/*
// @match http://www.psychonomic-journals.org/*
// @match https://www.psychonomic-journals.org/*
// @match http://www.publichealthreports.org/*
// @match https://www.publichealthreports.org/*
// @match http://library.queensu.ca/*
// @match https://library.queensu.ca/*
// @match http://pubs.rsna.org/*
// @match https://pubs.rsna.org/*
// @match http://www.srmjournals.org/*
// @match https://www.srmjournals.org/*
// @match http://www.reproduction-online.org/*
// @match https://www.reproduction-online.org/*
// @match http://biblioline.nisc.com/*
// @match https://biblioline.nisc.com/*
// @match http://db.riskwaters.com/*
// @match https://db.riskwaters.com/*
// @match http://www.rockefeller.edu/*
// @match https://www.rockefeller.edu/*
// @match http://www.jem.org/*
// @match https://www.jem.org/*
// @match http://www.rupress.org/*
// @match https://www.rupress.org/*
// @match http://rmmc.eas.asu.edu/*
// @match https://rmmc.eas.asu.edu/*
// @match http://www.romanticism.amdigital.co.uk/*
// @match https://www.romanticism.amdigital.co.uk/*
// @match http://www.rep.routledge.com/*
// @match https://www.rep.routledge.com/*
// @match http://www.rsc.org/*
// @match https://www.rsc.org/*
// @match http://www.rsnz.org/*
// @match https://www.rsnz.org/*
// @match http://journals.royalsociety.org/*
// @match https://journals.royalsociety.org/*
// @match http://royalsocietypublishing.org/*
// @match https://royalsocietypublishing.org/*
// @match http://www.csu.edu.au/*
// @match https://www.csu.edu.au/*
// @match http://escarpmentpress.org/*
// @match https://escarpmentpress.org/*
// @match http://reference.sabinet.co.za/*
// @match https://reference.sabinet.co.za/*
// @match http://digitallibrary.sae.org/*
// @match https://digitallibrary.sae.org/*
// @match http://sage-ereference.com/*
// @match https://sage-ereference.com/*
// @match http://knowledge.sagepub.com/*
// @match https://knowledge.sagepub.com/*
// @match http://online.sagepub.com/*
// @match https://online.sagepub.com/*
// @match http://www.sauerlaender-verlag.com/*
// @match https://www.sauerlaender-verlag.com/*
// @match http://www.schattauer.de/*
// @match https://www.schattauer.de/*
// @match http://www.sciandmed.com/*
// @match https://www.sciandmed.com/*
// @match http://www.trrjournalonline.trb.org/*
// @match https://www.trrjournalonline.trb.org/*
// @match http://www.wssajournals.org/*
// @match https://www.wssajournals.org/*
// @match http://www.hub.sciverse.com/*
// @match https://www.hub.sciverse.com/*
// @match http://www.sciencedirect.com/*
// @match https://www.sciencedirect.com/*
// @match http://www.scopus.com/*
// @match https://www.scopus.com/*
// @match http://www.sciencemag.org/*
// @match https://www.sciencemag.org/*
// @match http://sos.thieme.com/*
// @match https://sos.thieme.com/*
// @match http://utpjournals.metapress.com/*
// @match https://utpjournals.metapress.com/*
// @match http://sex.sagepub.com/*
// @match https://sex.sagepub.com/*
// @match http://www.sjmjournals.org/*
// @match https://www.sjmjournals.org/*
// @match http://www.shancocksltd.co.uk/*
// @match https://www.shancocksltd.co.uk/*
// @match http://epubs.siam.org/*
// @match https://epubs.siam.org/*
// @match http://www.journalsleep.org/*
// @match https://www.journalsleep.org/*
// @match http://glmu.alexanderstreet.com/*
// @match https://glmu.alexanderstreet.com/*
// @match http://sfaa.metapress.com/*
// @match https://sfaa.metapress.com/*
// @match http://www.endocrinology-journals.org/*
// @match https://www.endocrinology-journals.org/*
// @match http://library.seg.org/*
// @match https://library.seg.org/*
// @match http://www.sgm.ac.uk/*
// @match https://www.sgm.ac.uk/*
// @match http://www.rangelands.org/*
// @match https://www.rangelands.org/*
// @match http://journalofrheology.org/*
// @match https://journalofrheology.org/*
// @match http://www.ssr.org/*
// @match https://www.ssr.org/*
// @match http://www.oecd-ilibrary.org/*
// @match https://www.oecd-ilibrary.org/*
// @match http://www.oecd-nea.org/*
// @match https://www.oecd-nea.org/*
// @match http://www.oecdobserver.org/*
// @match https://www.oecdobserver.org/*
// @match http://new.sourceoecd.org/*
// @match https://new.sourceoecd.org/*
// @match http://www.spe.org/*
// @match https://www.spe.org/*
// @match http://spiedigitallibrary.org/*
// @match https://spiedigitallibrary.org/*
// @match http://ebooks.spiedigitallibrary.org/*
// @match https://ebooks.spiedigitallibrary.org/*
// @match http://spiedigitallibrary.aip.org/*
// @match https://spiedigitallibrary.aip.org/*
// @match http://journals.spiedigitallibrary.org/*
// @match https://journals.spiedigitallibrary.org/*
// @match http://opticalengineering.spiedigitallibrary.org/*
// @match https://opticalengineering.spiedigitallibrary.org/*
// @match http://biomedicaloptics.spiedigitallibrary.org/*
// @match https://biomedicaloptics.spiedigitallibrary.org/*
// @match http://link.springer.de/*
// @match https://link.springer.de/*
// @match http://link.springer.com/*
// @match https://link.springer.com/*
// @match http://materials.springer.com/*
// @match https://materials.springer.com/*
// @match http://www.saiglobal.com/*
// @match https://www.saiglobal.com/*
// @match http://www.stata-journal.com/*
// @match https://www.stata-journal.com/*
// @match http://www.stat.sinica.edu.tw/*
// @match https://www.stat.sinica.edu.tw/*
// @match http://www.statindex.org/*
// @match https://www.statindex.org/*
// @match http://stahlonline.cambridge.org/*
// @match https://stahlonline.cambridge.org/*
// @match http://www.surgeryjournal.co.uk/*
// @match https://www.surgeryjournal.co.uk/*
// @match http://www.hcn.net.au/*
// @match https://www.hcn.net.au/*
// @match http://www.law.usyd.edu.au/*
// @match https://www.law.usyd.edu.au/*
// @match http://archives.smh.com.au/*
// @match https://archives.smh.com.au/*
// @match http://www.arabidopsis.org/*
// @match https://www.arabidopsis.org/*
// @match http://tax.thomsonreuters.com.au/*
// @match https://tax.thomsonreuters.com.au/*
// @match http://tl2.idcpublishers.info/*
// @match https://tl2.idcpublishers.info/*
// @match http://www.tandfonline.com/*
// @match https://www.tandfonline.com/*
// @match http://technopress.kaist.ac.kr/*
// @match https://technopress.kaist.ac.kr/*
// @match http://journal.telospress.com/*
// @match https://journal.telospress.com/*
// @match http://www.terrapub.co.jp/*
// @match https://www.terrapub.co.jp/*
// @match http://jep.textrum.com/*
// @match https://jep.textrum.com/*
// @match http://www.economist.com/*
// @match https://www.economist.com/*
// @match http://stephanus.tlg.uci.edu/*
// @match https://stephanus.tlg.uci.edu/*
// @match http://xroads.virginia.edu/*
// @match https://xroads.virginia.edu/*
// @match http://www.theshakespearerecords.com/*
// @match https://www.theshakespearerecords.com/*
// @match http://www.escj.org/*
// @match https://www.escj.org/*
// @match http://archive.thewest.com.au/*
// @match https://archive.thewest.com.au/*
// @match http://www.thomastelford.com/*
// @match https://www.thomastelford.com/*
// @match http://www.tlemea.com/*
// @match https://www.tlemea.com/*
// @match http://archive.scijournal.com/*
// @match https://archive.scijournal.com/*
// @match http://transactionpub.metapress.com/*
// @match https://transactionpub.metapress.com/*
// @match http://trb.metapress.com/*
// @match https://trb.metapress.com/*
// @match http://www.scientific.net/*
// @match https://www.scientific.net/*
// @match http://www.triangle.co.uk/*
// @match https://www.triangle.co.uk/*
// @match http://turf.lib.msu.edu/*
// @match https://turf.lib.msu.edu/*
// @match http://www.turpion.org/*
// @match https://www.turpion.org/*
// @match http://ulrichsweb.serialssolutions.com/*
// @match https://ulrichsweb.serialssolutions.com/*
// @match http://untreaty.un.org/*
// @match https://untreaty.un.org/*
// @match http://157.150.195.4/*
// @match https://157.150.195.4/*
// @match http://www.journals.uchicago.edu/*
// @match https://www.journals.uchicago.edu/*
// @match http://www.press.uillinois.edu/*
// @match https://www.press.uillinois.edu/*
// @match http://www.uwpress.org/*
// @match https://www.uwpress.org/*
// @match http://www.universitypressscholarship.com/*
// @match https://www.universitypressscholarship.com/*
// @match http://www.v-r.de/*
// @match https://www.v-r.de/*
// @match http://wileyonlinelibrary.com/*
// @match https://wileyonlinelibrary.com/*
// @match http://wlt.metapress.com/*
// @match https://wlt.metapress.com/*
// @match http://elib.library.uwa.edu.au/*
// @match https://elib.library.uwa.edu.au/*
// @match http://erl.library.uwa.edu.au:8050/*
// @match https://erl.library.uwa.edu.au:8050/*
// @match http://etext.library.uwa.edu.au/*
// @match https://etext.library.uwa.edu.au/*
// @match http://findit.library.uwa.edu.au/*
// @match https://findit.library.uwa.edu.au/*
// @match http://www.victoriandatabase.com/*
// @match https://www.victoriandatabase.com/*
// @match http://www.degruyter.com/*
// @match https://www.degruyter.com/*
// @match http://www.victorianperiodicals.com/*
// @match https://www.victorianperiodicals.com/*
// @match http://wellesley.chadwyck.co.uk/*
// @match https://wellesley.chadwyck.co.uk/*
// @match http://web5s.silverplatter.com/*
// @match https://web5s.silverplatter.com/*
// @match http://westlaw.com.au/*
// @match https://westlaw.com.au/*
// @match http://login.westlaw.co.uk/*
// @match https://login.westlaw.co.uk/*
// @match http://www.westlaw.com/*
// @match https://www.westlaw.com/*
// @match http://connectweb.com.au/*
// @match https://connectweb.com.au/*
// @match http://hw.oeaw.ac.at/*
// @match https://hw.oeaw.ac.at/*
// @match http://www.withoutsanctuary.org/*
// @match https://www.withoutsanctuary.org/*
// @match http://journals.witpress.com/*
// @match https://journals.witpress.com/*
// @match http://www.worldbank.org/*
// @match https://www.worldbank.org/*
// @match http://newfirstsearch.oclc.org/*
// @match https://newfirstsearch.oclc.org/*
// @match http://worldcatlibraries.org/*
// @match https://worldcatlibraries.org/*
// @match http://www.worldscinet.com/*
// @match https://www.worldscinet.com/*
// @match http://www.worldscientific.com/*
// @match https://www.worldscientific.com/*
// @match http://ebooks.worldscinet.com/*
// @match https://ebooks.worldscinet.com/*
// @match http://www.worldshakesbib.org/*
// @match https://www.worldshakesbib.org/*
// @match http://naa12.naa.gov.au/*
// @match https://naa12.naa.gov.au/*
// @match http://www.meddent.uwa.edu.au/*
// @match https://www.meddent.uwa.edu.au/*
// ==/UserScript==

window.location.replace(window.location.href.replace(/(https?:\/\/)(.*)/i, "$1ezproxy.library.uwa.edu.au/login?url=$1$2"))
